# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Layout_1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 594)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 106, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Form.setPalette(palette)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_Viewports = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewports.sizePolicy().hasHeightForWidth())
        self.frame_Viewports.setSizePolicy(sizePolicy)
        self.frame_Viewports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewports.setObjectName("frame_Viewports")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Viewports)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_coronal = QtWidgets.QVBoxLayout()
        self.verticalLayout_coronal.setSpacing(0)
        self.verticalLayout_coronal.setObjectName("verticalLayout_coronal")
        self.vtk_panel_coronal = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_coronal.sizePolicy().hasHeightForWidth())
        self.vtk_panel_coronal.setSizePolicy(sizePolicy)
        self.vtk_panel_coronal.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_coronal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_coronal.setLineWidth(0)
        self.vtk_panel_coronal.setObjectName("vtk_panel_coronal")
        self.verticalLayout_coronal.addWidget(self.vtk_panel_coronal)
        self.SubPanel_coronal = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_coronal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_coronal.sizePolicy().hasHeightForWidth())
        self.SubPanel_coronal.setSizePolicy(sizePolicy)
        self.SubPanel_coronal.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_coronal.setStyleSheet("background-color: rgba(50, 50, 50,50);")
        self.SubPanel_coronal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_coronal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_coronal.setObjectName("SubPanel_coronal")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.SubPanel_coronal)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Slider_coronal = QtWidgets.QSlider(self.SubPanel_coronal)
        self.Slider_coronal.setAutoFillBackground(False)
        self.Slider_coronal.setStyleSheet("")
        self.Slider_coronal.setProperty("value", 50)
        self.Slider_coronal.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_coronal.setObjectName("Slider_coronal")
        self.horizontalLayout_4.addWidget(self.Slider_coronal)
        self.sliceNum_coronal = QtWidgets.QLabel(self.SubPanel_coronal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_coronal.sizePolicy().hasHeightForWidth())
        self.sliceNum_coronal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_coronal.setFont(font)
        self.sliceNum_coronal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_coronal.setObjectName("sliceNum_coronal")
        self.horizontalLayout_4.addWidget(self.sliceNum_coronal)
        self.sliceNum_axial_4 = QtWidgets.QLabel(self.SubPanel_coronal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_4.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_4.setFont(font)
        self.sliceNum_axial_4.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_4.setObjectName("sliceNum_axial_4")
        self.horizontalLayout_4.addWidget(self.sliceNum_axial_4)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_coronal.addWidget(self.SubPanel_coronal)
        self.verticalLayout_coronal.setStretch(0, 20)
        self.verticalLayout_coronal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_coronal, 1, 0, 1, 1)
        self.verticalLayout_sagittal = QtWidgets.QVBoxLayout()
        self.verticalLayout_sagittal.setSpacing(0)
        self.verticalLayout_sagittal.setObjectName("verticalLayout_sagittal")
        self.vtk_panel_sagittal = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_sagittal.sizePolicy().hasHeightForWidth())
        self.vtk_panel_sagittal.setSizePolicy(sizePolicy)
        self.vtk_panel_sagittal.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_sagittal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_sagittal.setLineWidth(0)
        self.vtk_panel_sagittal.setObjectName("vtk_panel_sagittal")
        self.verticalLayout_sagittal.addWidget(self.vtk_panel_sagittal)
        self.SubPanel_sagittal = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_sagittal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_sagittal.sizePolicy().hasHeightForWidth())
        self.SubPanel_sagittal.setSizePolicy(sizePolicy)
        self.SubPanel_sagittal.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_sagittal.setStyleSheet("background-color: rgba(50, 50, 50,50);")
        self.SubPanel_sagittal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_sagittal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_sagittal.setObjectName("SubPanel_sagittal")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SubPanel_sagittal)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Slider_sagittal = QtWidgets.QSlider(self.SubPanel_sagittal)
        self.Slider_sagittal.setAutoFillBackground(False)
        self.Slider_sagittal.setStyleSheet("")
        self.Slider_sagittal.setProperty("value", 50)
        self.Slider_sagittal.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_sagittal.setObjectName("Slider_sagittal")
        self.horizontalLayout_3.addWidget(self.Slider_sagittal)
        self.sliceNum_sagittal = QtWidgets.QLabel(self.SubPanel_sagittal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_sagittal.sizePolicy().hasHeightForWidth())
        self.sliceNum_sagittal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_sagittal.setFont(font)
        self.sliceNum_sagittal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_sagittal.setObjectName("sliceNum_sagittal")
        self.horizontalLayout_3.addWidget(self.sliceNum_sagittal)
        self.sliceNum_axial_3 = QtWidgets.QLabel(self.SubPanel_sagittal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_3.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_3.setFont(font)
        self.sliceNum_axial_3.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_3.setObjectName("sliceNum_axial_3")
        self.horizontalLayout_3.addWidget(self.sliceNum_axial_3)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_sagittal.addWidget(self.SubPanel_sagittal)
        self.verticalLayout_sagittal.setStretch(0, 20)
        self.verticalLayout_sagittal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_sagittal, 1, 1, 1, 1)
        self.verticalLayout_axial = QtWidgets.QVBoxLayout()
        self.verticalLayout_axial.setSpacing(0)
        self.verticalLayout_axial.setObjectName("verticalLayout_axial")
        self.vtk_panel_axial = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_axial.sizePolicy().hasHeightForWidth())
        self.vtk_panel_axial.setSizePolicy(sizePolicy)
        self.vtk_panel_axial.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_axial.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_axial.setLineWidth(0)
        self.vtk_panel_axial.setObjectName("vtk_panel_axial")
        self.verticalLayout_axial.addWidget(self.vtk_panel_axial)
        self.SubPanel_axial = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_axial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_axial.sizePolicy().hasHeightForWidth())
        self.SubPanel_axial.setSizePolicy(sizePolicy)
        self.SubPanel_axial.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_axial.setAutoFillBackground(False)
        self.SubPanel_axial.setStyleSheet("background-color: rgba(50, 50, 50, 50);")
        self.SubPanel_axial.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_axial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_axial.setObjectName("SubPanel_axial")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.SubPanel_axial)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Slider_axial = QtWidgets.QSlider(self.SubPanel_axial)
        self.Slider_axial.setAutoFillBackground(False)
        self.Slider_axial.setStyleSheet("")
        self.Slider_axial.setProperty("value", 50)
        self.Slider_axial.setTracking(True)
        self.Slider_axial.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_axial.setInvertedAppearance(False)
        self.Slider_axial.setInvertedControls(False)
        self.Slider_axial.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_axial.setObjectName("Slider_axial")
        self.horizontalLayout_2.addWidget(self.Slider_axial)
        self.sliceNum_axial = QtWidgets.QLabel(self.SubPanel_axial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial.setFont(font)
        self.sliceNum_axial.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial.setObjectName("sliceNum_axial")
        self.horizontalLayout_2.addWidget(self.sliceNum_axial)
        self.sliceNum_axial_2 = QtWidgets.QLabel(self.SubPanel_axial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_2.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_2.setFont(font)
        self.sliceNum_axial_2.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_2.setObjectName("sliceNum_axial_2")
        self.horizontalLayout_2.addWidget(self.sliceNum_axial_2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_axial.addWidget(self.SubPanel_axial)
        self.verticalLayout_axial.setStretch(0, 20)
        self.verticalLayout_axial.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_axial, 0, 1, 1, 1)
        self.verticalLayout_3D = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D.setSpacing(0)
        self.verticalLayout_3D.setObjectName("verticalLayout_3D")
        self.vtk_panel_3D = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D.setSizePolicy(sizePolicy)
        self.vtk_panel_3D.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_3D.setAutoFillBackground(False)
        self.vtk_panel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D.setLineWidth(0)
        self.vtk_panel_3D.setObjectName("vtk_panel_3D")
        self.verticalLayout_3D.addWidget(self.vtk_panel_3D)
        self.SubPanel_3D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D.setSizePolicy(sizePolicy)
        self.SubPanel_3D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D.setStyleSheet("background-color: rgba(50, 50, 50,50);")
        self.SubPanel_3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D.setObjectName("SubPanel_3D")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SubPanel_3D)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sliceNum_axial_6 = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_6.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_6.setFont(font)
        self.sliceNum_axial_6.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_6.setObjectName("sliceNum_axial_6")
        self.horizontalLayout_5.addWidget(self.sliceNum_axial_6)
        self.sliceNum_axial_5 = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_5.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_5.setFont(font)
        self.sliceNum_axial_5.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_5.setObjectName("sliceNum_axial_5")
        self.horizontalLayout_5.addWidget(self.sliceNum_axial_5)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3D.addWidget(self.SubPanel_3D)
        self.verticalLayout_3D.setStretch(0, 20)
        self.verticalLayout_3D.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_3D, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_Viewports, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sliceNum_coronal.setText(_translate("Form", "50"))
        self.sliceNum_axial_4.setText(_translate("Form", "Coronal"))
        self.sliceNum_sagittal.setText(_translate("Form", "50"))
        self.sliceNum_axial_3.setText(_translate("Form", "Sagittal"))
        self.sliceNum_axial.setText(_translate("Form", "50"))
        self.sliceNum_axial_2.setText(_translate("Form", "Axial"))
        self.sliceNum_axial_6.setText(_translate("Form", "Virtual"))
        self.sliceNum_axial_5.setText(_translate("Form", "3D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
