# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWin.resize(1273, 941)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWin.sizePolicy().hasHeightForWidth())
        MainWin.setSizePolicy(sizePolicy)
        MainWin.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWin.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/BronchoVision.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWin.setWindowIcon(icon)
        MainWin.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWin.setAutoFillBackground(False)
        MainWin.setIconSize(QtCore.QSize(40, 40))
        MainWin.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setStyleSheet("")
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame_Left = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Left.sizePolicy().hasHeightForWidth())
        self.frame_Left.setSizePolicy(sizePolicy)
        self.frame_Left.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_Left.setAutoFillBackground(False)
        self.frame_Left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_Left.setLineWidth(1)
        self.frame_Left.setMidLineWidth(0)
        self.frame_Left.setObjectName("frame_Left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Left)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_Left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(50, 50,50);\n"
"color: rgb(157, 205, 216);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_patients = QtWidgets.QWidget()
        self.tab_patients.setObjectName("tab_patients")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_patients)
        self.verticalLayout_11.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_NewPatient = QtWidgets.QToolButton(self.tab_patients)
        self.btn_NewPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_NewPatient.sizePolicy().hasHeightForWidth())
        self.btn_NewPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_NewPatient.setFont(font)
        self.btn_NewPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_NewPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_NewPatient.setAutoFillBackground(False)
        self.btn_NewPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/add_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_NewPatient.setIcon(icon1)
        self.btn_NewPatient.setIconSize(QtCore.QSize(40, 40))
        self.btn_NewPatient.setCheckable(False)
        self.btn_NewPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_NewPatient.setAutoRaise(True)
        self.btn_NewPatient.setObjectName("btn_NewPatient")
        self.verticalLayout_11.addWidget(self.btn_NewPatient)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem1)
        self.groupBox_Patients = QtWidgets.QGroupBox(self.tab_patients)
        self.groupBox_Patients.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Patients.setFont(font)
        self.groupBox_Patients.setAutoFillBackground(False)
        self.groupBox_Patients.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Patients.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Patients.setFlat(True)
        self.groupBox_Patients.setCheckable(False)
        self.groupBox_Patients.setObjectName("groupBox_Patients")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_Patients)
        self.verticalLayout_12.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget_Patients = QtWidgets.QTableWidget(self.groupBox_Patients)
        self.tableWidget_Patients.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_Patients.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Patients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Patients.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget_Patients.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_Patients.setWordWrap(False)
        self.tableWidget_Patients.setRowCount(0)
        self.tableWidget_Patients.setObjectName("tableWidget_Patients")
        self.tableWidget_Patients.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Patients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Patients.setHorizontalHeaderItem(1, item)
        self.tableWidget_Patients.horizontalHeader().setVisible(False)
        self.tableWidget_Patients.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Patients.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_Patients.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Patients.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_Patients.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Patients.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableWidget_Patients)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_15.setSpacing(7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_LoadPatient = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_LoadPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadPatient.sizePolicy().hasHeightForWidth())
        self.btn_LoadPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_LoadPatient.setFont(font)
        self.btn_LoadPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadPatient.setAutoFillBackground(False)
        self.btn_LoadPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/load_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadPatient.setIcon(icon2)
        self.btn_LoadPatient.setIconSize(QtCore.QSize(35, 35))
        self.btn_LoadPatient.setCheckable(False)
        self.btn_LoadPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadPatient.setAutoRaise(True)
        self.btn_LoadPatient.setObjectName("btn_LoadPatient")
        self.horizontalLayout_15.addWidget(self.btn_LoadPatient)
        self.btn_DeletePatient = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_DeletePatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_DeletePatient.sizePolicy().hasHeightForWidth())
        self.btn_DeletePatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_DeletePatient.setFont(font)
        self.btn_DeletePatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_DeletePatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_DeletePatient.setAutoFillBackground(False)
        self.btn_DeletePatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/delete_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_DeletePatient.setIcon(icon3)
        self.btn_DeletePatient.setIconSize(QtCore.QSize(35, 35))
        self.btn_DeletePatient.setCheckable(False)
        self.btn_DeletePatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_DeletePatient.setAutoRaise(True)
        self.btn_DeletePatient.setObjectName("btn_DeletePatient")
        self.horizontalLayout_15.addWidget(self.btn_DeletePatient)
        self.horizontalLayout_15.setStretch(0, 2)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_11.addWidget(self.groupBox_Patients)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(7, 0, 7, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_ImportPatient = QtWidgets.QToolButton(self.tab_patients)
        self.btn_ImportPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ImportPatient.sizePolicy().hasHeightForWidth())
        self.btn_ImportPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ImportPatient.setFont(font)
        self.btn_ImportPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ImportPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ImportPatient.setAutoFillBackground(False)
        self.btn_ImportPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_ImportPatient.setIconSize(QtCore.QSize(50, 50))
        self.btn_ImportPatient.setCheckable(False)
        self.btn_ImportPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ImportPatient.setAutoRaise(True)
        self.btn_ImportPatient.setObjectName("btn_ImportPatient")
        self.horizontalLayout_10.addWidget(self.btn_ImportPatient)
        self.btn_ClearPatients = QtWidgets.QToolButton(self.tab_patients)
        self.btn_ClearPatients.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ClearPatients.sizePolicy().hasHeightForWidth())
        self.btn_ClearPatients.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ClearPatients.setFont(font)
        self.btn_ClearPatients.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ClearPatients.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ClearPatients.setAutoFillBackground(False)
        self.btn_ClearPatients.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_ClearPatients.setIconSize(QtCore.QSize(50, 50))
        self.btn_ClearPatients.setCheckable(False)
        self.btn_ClearPatients.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ClearPatients.setAutoRaise(True)
        self.btn_ClearPatients.setObjectName("btn_ClearPatients")
        self.horizontalLayout_10.addWidget(self.btn_ClearPatients)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_patients, "")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_14.setContentsMargins(5, 20, 5, 5)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_Viewports = QtWidgets.QGroupBox(self.tab_view)
        self.groupBox_Viewports.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Viewports.setFont(font)
        self.groupBox_Viewports.setAutoFillBackground(False)
        self.groupBox_Viewports.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Viewports.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Viewports.setFlat(True)
        self.groupBox_Viewports.setCheckable(False)
        self.groupBox_Viewports.setObjectName("groupBox_Viewports")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Viewports)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.comboBox_2DView = QtWidgets.QComboBox(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2DView.sizePolicy().hasHeightForWidth())
        self.comboBox_2DView.setSizePolicy(sizePolicy)
        self.comboBox_2DView.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.comboBox_2DView.setFont(font)
        self.comboBox_2DView.setAutoFillBackground(False)
        self.comboBox_2DView.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.comboBox_2DView.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_2DView.setFrame(False)
        self.comboBox_2DView.setObjectName("comboBox_2DView")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_2DView)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.slider_threshold3D = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D.setEnabled(False)
        self.slider_threshold3D.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.slider_threshold3D.setMinimum(-2000)
        self.slider_threshold3D.setMaximum(1000)
        self.slider_threshold3D.setSingleStep(10)
        self.slider_threshold3D.setPageStep(100)
        self.slider_threshold3D.setProperty("value", -600)
        self.slider_threshold3D.setTracking(False)
        self.slider_threshold3D.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D.setObjectName("slider_threshold3D")
        self.horizontalLayout_12.addWidget(self.slider_threshold3D)
        self.lbl_threshold3D = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D.setSizePolicy(sizePolicy)
        self.lbl_threshold3D.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_threshold3D.setFont(font)
        self.lbl_threshold3D.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D.setObjectName("lbl_threshold3D")
        self.horizontalLayout_12.addWidget(self.lbl_threshold3D)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.slider_threshold3D_2 = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D_2.setEnabled(False)
        self.slider_threshold3D_2.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.slider_threshold3D_2.setMinimum(-2000)
        self.slider_threshold3D_2.setMaximum(1000)
        self.slider_threshold3D_2.setSingleStep(10)
        self.slider_threshold3D_2.setPageStep(100)
        self.slider_threshold3D_2.setProperty("value", -600)
        self.slider_threshold3D_2.setTracking(False)
        self.slider_threshold3D_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D_2.setObjectName("slider_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.slider_threshold3D_2)
        self.lbl_threshold3D_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D_2.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D_2.setSizePolicy(sizePolicy)
        self.lbl_threshold3D_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_threshold3D_2.setFont(font)
        self.lbl_threshold3D_2.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D_2.setObjectName("lbl_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.lbl_threshold3D_2)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 2)
        self.horizontalLayout_14.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.btn_ResetViewports = QtWidgets.QToolButton(self.groupBox_Viewports)
        self.btn_ResetViewports.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetViewports.sizePolicy().hasHeightForWidth())
        self.btn_ResetViewports.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetViewports.setFont(font)
        self.btn_ResetViewports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetViewports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetViewports.setAutoFillBackground(False)
        self.btn_ResetViewports.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/resetViews.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetViewports.setIcon(icon4)
        self.btn_ResetViewports.setIconSize(QtCore.QSize(50, 50))
        self.btn_ResetViewports.setCheckable(False)
        self.btn_ResetViewports.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetViewports.setAutoRaise(True)
        self.btn_ResetViewports.setObjectName("btn_ResetViewports")
        self.verticalLayout_5.addWidget(self.btn_ResetViewports)
        self.verticalLayout_14.addWidget(self.groupBox_Viewports)
        self.tabWidget.addTab(self.tab_view, "")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_process)
        self.verticalLayout_16.setContentsMargins(5, 20, 5, 5)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_segmentation = QtWidgets.QGroupBox(self.tab_process)
        self.groupBox_segmentation.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_segmentation.setFont(font)
        self.groupBox_segmentation.setAutoFillBackground(False)
        self.groupBox_segmentation.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_segmentation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_segmentation.setFlat(True)
        self.groupBox_segmentation.setCheckable(False)
        self.groupBox_segmentation.setObjectName("groupBox_segmentation")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_segmentation)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_Segment = QtWidgets.QToolButton(self.groupBox_segmentation)
        self.btn_Segment.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Segment.sizePolicy().hasHeightForWidth())
        self.btn_Segment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Segment.setFont(font)
        self.btn_Segment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Segment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Segment.setAutoFillBackground(False)
        self.btn_Segment.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/Segmentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Segment.setIcon(icon5)
        self.btn_Segment.setIconSize(QtCore.QSize(50, 50))
        self.btn_Segment.setCheckable(False)
        self.btn_Segment.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Segment.setAutoRaise(True)
        self.btn_Segment.setObjectName("btn_Segment")
        self.verticalLayout_15.addWidget(self.btn_Segment)
        self.btn_Centerline = QtWidgets.QToolButton(self.groupBox_segmentation)
        self.btn_Centerline.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Centerline.sizePolicy().hasHeightForWidth())
        self.btn_Centerline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Centerline.setFont(font)
        self.btn_Centerline.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Centerline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Centerline.setAutoFillBackground(False)
        self.btn_Centerline.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/centerLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Centerline.setIcon(icon6)
        self.btn_Centerline.setIconSize(QtCore.QSize(50, 50))
        self.btn_Centerline.setCheckable(False)
        self.btn_Centerline.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Centerline.setAutoRaise(True)
        self.btn_Centerline.setObjectName("btn_Centerline")
        self.verticalLayout_15.addWidget(self.btn_Centerline)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem7)
        self.verticalLayout_16.addWidget(self.groupBox_segmentation)
        self.tabWidget.addTab(self.tab_process, "")
        self.tab_tracking = QtWidgets.QWidget()
        self.tab_tracking.setObjectName("tab_tracking")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_tracking)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_tracking)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("background-color: rgb(50, 50,50);")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_online = QtWidgets.QWidget()
        self.tabWidget_online.setEnabled(True)
        self.tabWidget_online.setObjectName("tabWidget_online")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidget_online)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.tabWidget_online)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Connect = QtWidgets.QToolButton(self.frame_2)
        self.btn_Connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Connect.sizePolicy().hasHeightForWidth())
        self.btn_Connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Connect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Connect.setAutoFillBackground(False)
        self.btn_Connect.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"selection-background-color: rgb(85, 85, 255);\n"
"alternate-background-color: rgb(85, 255, 127);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/tracker_disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Connect.setIcon(icon7)
        self.btn_Connect.setIconSize(QtCore.QSize(50, 50))
        self.btn_Connect.setCheckable(False)
        self.btn_Connect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Connect.setAutoRaise(True)
        self.btn_Connect.setObjectName("btn_Connect")
        self.verticalLayout_4.addWidget(self.btn_Connect)
        self.btn_ToolsWindow = QtWidgets.QToolButton(self.frame_2)
        self.btn_ToolsWindow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ToolsWindow.sizePolicy().hasHeightForWidth())
        self.btn_ToolsWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ToolsWindow.setFont(font)
        self.btn_ToolsWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ToolsWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ToolsWindow.setAutoFillBackground(False)
        self.btn_ToolsWindow.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/Tools_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ToolsWindow.setIcon(icon8)
        self.btn_ToolsWindow.setIconSize(QtCore.QSize(50, 50))
        self.btn_ToolsWindow.setCheckable(False)
        self.btn_ToolsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ToolsWindow.setAutoRaise(True)
        self.btn_ToolsWindow.setObjectName("btn_ToolsWindow")
        self.verticalLayout_4.addWidget(self.btn_ToolsWindow)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.btn_recordToolRef = QtWidgets.QToolButton(self.frame_2)
        self.btn_recordToolRef.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_recordToolRef.sizePolicy().hasHeightForWidth())
        self.btn_recordToolRef.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_recordToolRef.setFont(font)
        self.btn_recordToolRef.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_recordToolRef.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_recordToolRef.setAutoFillBackground(False)
        self.btn_recordToolRef.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"border-color: rgb(255, 78, 81);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/rec_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_recordToolRef.setIcon(icon9)
        self.btn_recordToolRef.setIconSize(QtCore.QSize(50, 50))
        self.btn_recordToolRef.setCheckable(False)
        self.btn_recordToolRef.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_recordToolRef.setAutoRaise(True)
        self.btn_recordToolRef.setObjectName("btn_recordToolRef")
        self.verticalLayout_4.addWidget(self.btn_recordToolRef)
        self.btn_registerCenterlines = QtWidgets.QToolButton(self.frame_2)
        self.btn_registerCenterlines.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_registerCenterlines.sizePolicy().hasHeightForWidth())
        self.btn_registerCenterlines.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_registerCenterlines.setFont(font)
        self.btn_registerCenterlines.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_registerCenterlines.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_registerCenterlines.setAutoFillBackground(False)
        self.btn_registerCenterlines.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/register_centerlines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_registerCenterlines.setIcon(icon10)
        self.btn_registerCenterlines.setIconSize(QtCore.QSize(50, 50))
        self.btn_registerCenterlines.setCheckable(False)
        self.btn_registerCenterlines.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_registerCenterlines.setAutoRaise(True)
        self.btn_registerCenterlines.setObjectName("btn_registerCenterlines")
        self.verticalLayout_4.addWidget(self.btn_registerCenterlines)
        spacerItem9 = QtWidgets.QSpacerItem(20, 263, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.tabWidget_2.addTab(self.tabWidget_online, "")
        self.tabWidget_offline = QtWidgets.QWidget()
        self.tabWidget_offline.setEnabled(False)
        self.tabWidget_offline.setObjectName("tabWidget_offline")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabWidget_offline)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.tabWidget_offline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(50, 50,50);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LoadRefPoints = QtWidgets.QToolButton(self.frame)
        self.btn_LoadRefPoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadRefPoints.sizePolicy().hasHeightForWidth())
        self.btn_LoadRefPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_LoadRefPoints.setFont(font)
        self.btn_LoadRefPoints.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadRefPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadRefPoints.setAutoFillBackground(False)
        self.btn_LoadRefPoints.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/trajectory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadRefPoints.setIcon(icon11)
        self.btn_LoadRefPoints.setIconSize(QtCore.QSize(50, 50))
        self.btn_LoadRefPoints.setCheckable(False)
        self.btn_LoadRefPoints.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadRefPoints.setAutoRaise(True)
        self.btn_LoadRefPoints.setObjectName("btn_LoadRefPoints")
        self.verticalLayout_3.addWidget(self.btn_LoadRefPoints)
        self.btn_LoadPoints = QtWidgets.QToolButton(self.frame)
        self.btn_LoadPoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadPoints.sizePolicy().hasHeightForWidth())
        self.btn_LoadPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_LoadPoints.setFont(font)
        self.btn_LoadPoints.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadPoints.setAutoFillBackground(False)
        self.btn_LoadPoints.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_LoadPoints.setIcon(icon11)
        self.btn_LoadPoints.setIconSize(QtCore.QSize(50, 50))
        self.btn_LoadPoints.setCheckable(False)
        self.btn_LoadPoints.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadPoints.setAutoRaise(True)
        self.btn_LoadPoints.setObjectName("btn_LoadPoints")
        self.verticalLayout_3.addWidget(self.btn_LoadPoints)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.slider_Frames = QtWidgets.QSlider(self.frame)
        self.slider_Frames.setEnabled(False)
        self.slider_Frames.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Frames.setObjectName("slider_Frames")
        self.horizontalLayout_13.addWidget(self.slider_Frames)
        self.lbl_FrameNum = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FrameNum.sizePolicy().hasHeightForWidth())
        self.lbl_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_FrameNum.setFont(font)
        self.lbl_FrameNum.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_FrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FrameNum.setObjectName("lbl_FrameNum")
        self.horizontalLayout_13.addWidget(self.lbl_FrameNum)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_camButtons_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_camButtons_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_camButtons_3.setSpacing(0)
        self.horizontalLayout_camButtons_3.setObjectName("horizontalLayout_camButtons_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem10)
        self.btn_playCam = QtWidgets.QToolButton(self.frame)
        self.btn_playCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_playCam.sizePolicy().hasHeightForWidth())
        self.btn_playCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playCam.setFont(font)
        self.btn_playCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_playCam.setAutoFillBackground(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_playCam.setIcon(icon12)
        self.btn_playCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_playCam.setAutoRaise(True)
        self.btn_playCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_playCam.setObjectName("btn_playCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_playCam)
        self.btn_pauseCam = QtWidgets.QToolButton(self.frame)
        self.btn_pauseCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pauseCam.sizePolicy().hasHeightForWidth())
        self.btn_pauseCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pauseCam.setFont(font)
        self.btn_pauseCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pauseCam.setAutoFillBackground(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pauseCam.setIcon(icon13)
        self.btn_pauseCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_pauseCam.setAutoRaise(True)
        self.btn_pauseCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_pauseCam.setObjectName("btn_pauseCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_pauseCam)
        self.btn_stopCam = QtWidgets.QToolButton(self.frame)
        self.btn_stopCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stopCam.sizePolicy().hasHeightForWidth())
        self.btn_stopCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stopCam.setFont(font)
        self.btn_stopCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stopCam.setAutoFillBackground(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stopCam.setIcon(icon14)
        self.btn_stopCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_stopCam.setAutoRaise(True)
        self.btn_stopCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_stopCam.setObjectName("btn_stopCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_stopCam)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_camButtons_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.checkBox_showPoints = QtWidgets.QCheckBox(self.frame)
        self.checkBox_showPoints.setEnabled(False)
        self.checkBox_showPoints.setChecked(False)
        self.checkBox_showPoints.setObjectName("checkBox_showPoints")
        self.verticalLayout_3.addWidget(self.checkBox_showPoints)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.btn_ResetVB = QtWidgets.QToolButton(self.frame)
        self.btn_ResetVB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetVB.sizePolicy().hasHeightForWidth())
        self.btn_ResetVB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetVB.setFont(font)
        self.btn_ResetVB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetVB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetVB.setAutoFillBackground(False)
        self.btn_ResetVB.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetVB.setIcon(icon15)
        self.btn_ResetVB.setIconSize(QtCore.QSize(50, 50))
        self.btn_ResetVB.setCheckable(False)
        self.btn_ResetVB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetVB.setAutoRaise(True)
        self.btn_ResetVB.setObjectName("btn_ResetVB")
        self.verticalLayout_3.addWidget(self.btn_ResetVB)
        self.verticalLayout_7.addWidget(self.frame)
        self.tabWidget_2.addTab(self.tabWidget_offline, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.btn_regMat = QtWidgets.QToolButton(self.tab_tracking)
        self.btn_regMat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_regMat.sizePolicy().hasHeightForWidth())
        self.btn_regMat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_regMat.setFont(font)
        self.btn_regMat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regMat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_regMat.setAutoFillBackground(False)
        self.btn_regMat.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/icons/matrix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regMat.setIcon(icon16)
        self.btn_regMat.setIconSize(QtCore.QSize(50, 50))
        self.btn_regMat.setCheckable(False)
        self.btn_regMat.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_regMat.setAutoRaise(True)
        self.btn_regMat.setObjectName("btn_regMat")
        self.verticalLayout_2.addWidget(self.btn_regMat)
        self.tabWidget.addTab(self.tab_tracking, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_Logo = QtWidgets.QLabel(self.frame_Left)
        self.label_Logo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Logo.sizePolicy().hasHeightForWidth())
        self.label_Logo.setSizePolicy(sizePolicy)
        self.label_Logo.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_Logo.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_Logo.setLineWidth(0)
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap(":/logo/logo/logo_transparent.png"))
        self.label_Logo.setScaledContents(True)
        self.label_Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Logo.setObjectName("label_Logo")
        self.verticalLayout.addWidget(self.label_Logo)
        self.label_version = QtWidgets.QLabel(self.frame_Left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(157, 205, 216);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.verticalLayout.addWidget(self.label_version)
        self.frame_Viewports = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewports.sizePolicy().hasHeightForWidth())
        self.frame_Viewports.setSizePolicy(sizePolicy)
        self.frame_Viewports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewports.setObjectName("frame_Viewports")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Viewports)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3D = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D.setSpacing(0)
        self.verticalLayout_3D.setObjectName("verticalLayout_3D")
        self.vtk_panel_3D_1 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_1.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_1.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_1.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.vtk_panel_3D_1.setPalette(palette)
        self.vtk_panel_3D_1.setAutoFillBackground(False)
        self.vtk_panel_3D_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_1.setLineWidth(0)
        self.vtk_panel_3D_1.setObjectName("vtk_panel_3D_1")
        self.verticalLayout_3D.addWidget(self.vtk_panel_3D_1)
        self.SubPanel_3D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D.setSizePolicy(sizePolicy)
        self.SubPanel_3D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D.setObjectName("SubPanel_3D")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SubPanel_3D)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.view1_desc = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view1_desc.sizePolicy().hasHeightForWidth())
        self.view1_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view1_desc.setFont(font)
        self.view1_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view1_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.view1_desc.setObjectName("view1_desc")
        self.horizontalLayout_5.addWidget(self.view1_desc)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3D.addWidget(self.SubPanel_3D)
        self.verticalLayout_3D.setStretch(0, 20)
        self.verticalLayout_3D.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_3D, 0, 0, 1, 1)
        self.verticalLayout_coronal = QtWidgets.QVBoxLayout()
        self.verticalLayout_coronal.setSpacing(0)
        self.verticalLayout_coronal.setObjectName("verticalLayout_coronal")
        self.vtk_panel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_endoscope.sizePolicy().hasHeightForWidth())
        self.vtk_panel_endoscope.setSizePolicy(sizePolicy)
        self.vtk_panel_endoscope.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_endoscope.setLineWidth(0)
        self.vtk_panel_endoscope.setObjectName("vtk_panel_endoscope")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.vtk_panel_endoscope)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_coronal.addWidget(self.vtk_panel_endoscope)
        self.SubPanel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_endoscope.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_endoscope.sizePolicy().hasHeightForWidth())
        self.SubPanel_endoscope.setSizePolicy(sizePolicy)
        self.SubPanel_endoscope.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_endoscope.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_endoscope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_endoscope.setObjectName("SubPanel_endoscope")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.SubPanel_endoscope)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.view3_desc = QtWidgets.QLabel(self.SubPanel_endoscope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3_desc.sizePolicy().hasHeightForWidth())
        self.view3_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view3_desc.setFont(font)
        self.view3_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view3_desc.setObjectName("view3_desc")
        self.horizontalLayout_4.addWidget(self.view3_desc)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_coronal.addWidget(self.SubPanel_endoscope)
        self.verticalLayout_coronal.setStretch(0, 20)
        self.verticalLayout_coronal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_coronal, 1, 0, 1, 1)
        self.verticalLayout_sagittal = QtWidgets.QVBoxLayout()
        self.verticalLayout_sagittal.setSpacing(0)
        self.verticalLayout_sagittal.setObjectName("verticalLayout_sagittal")
        self.vtk_panel_2D = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_2D.sizePolicy().hasHeightForWidth())
        self.vtk_panel_2D.setSizePolicy(sizePolicy)
        self.vtk_panel_2D.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_2D.setLineWidth(0)
        self.vtk_panel_2D.setObjectName("vtk_panel_2D")
        self.verticalLayout_sagittal.addWidget(self.vtk_panel_2D)
        self.SubPanel_2D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_2D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_2D.sizePolicy().hasHeightForWidth())
        self.SubPanel_2D.setSizePolicy(sizePolicy)
        self.SubPanel_2D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_2D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_2D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_2D.setObjectName("SubPanel_2D")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SubPanel_2D)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Slider_2D = QtWidgets.QSlider(self.SubPanel_2D)
        self.Slider_2D.setAutoFillBackground(False)
        self.Slider_2D.setStyleSheet("")
        self.Slider_2D.setProperty("value", 50)
        self.Slider_2D.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2D.setObjectName("Slider_2D")
        self.horizontalLayout_3.addWidget(self.Slider_2D)
        self.sliceNum_sagittal = QtWidgets.QLabel(self.SubPanel_2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_sagittal.sizePolicy().hasHeightForWidth())
        self.sliceNum_sagittal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_sagittal.setFont(font)
        self.sliceNum_sagittal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_sagittal.setObjectName("sliceNum_sagittal")
        self.horizontalLayout_3.addWidget(self.sliceNum_sagittal)
        self.view4_title = QtWidgets.QLabel(self.SubPanel_2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view4_title.sizePolicy().hasHeightForWidth())
        self.view4_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view4_title.setFont(font)
        self.view4_title.setStyleSheet("color: rgb(157, 205, 216);")
        self.view4_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.view4_title.setObjectName("view4_title")
        self.horizontalLayout_3.addWidget(self.view4_title)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_sagittal.addWidget(self.SubPanel_2D)
        self.verticalLayout_sagittal.setStretch(0, 20)
        self.verticalLayout_sagittal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_sagittal, 1, 1, 1, 1)
        self.verticalLayout_axial = QtWidgets.QVBoxLayout()
        self.verticalLayout_axial.setSpacing(0)
        self.verticalLayout_axial.setObjectName("verticalLayout_axial")
        self.vtk_panel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_2.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_2.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_2.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_2.setLineWidth(0)
        self.vtk_panel_3D_2.setObjectName("vtk_panel_3D_2")
        self.verticalLayout_axial.addWidget(self.vtk_panel_3D_2)
        self.SubPanel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D_2.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D_2.setSizePolicy(sizePolicy)
        self.SubPanel_3D_2.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D_2.setAutoFillBackground(False)
        self.SubPanel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D_2.setObjectName("SubPanel_3D_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.SubPanel_3D_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view2_desc = QtWidgets.QLabel(self.SubPanel_3D_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2_desc.sizePolicy().hasHeightForWidth())
        self.view2_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view2_desc.setFont(font)
        self.view2_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view2_desc.setObjectName("view2_desc")
        self.horizontalLayout_2.addWidget(self.view2_desc)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_axial.addWidget(self.SubPanel_3D_2)
        self.verticalLayout_axial.setStretch(0, 20)
        self.verticalLayout_axial.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_axial, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.splitter)
        MainWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setMouseTracking(False)
        self.toolBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setStyleSheet("color: rgb(98, 185, 189);")
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Image = QtWidgets.QAction(MainWin)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/icons/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon17)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionLoad_Image.setFont(font)
        self.actionLoad_Image.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionLoad_Image.setIconVisibleInMenu(True)
        self.actionLoad_Image.setProperty("shortcutVisibleInContextMenu", False)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionExit = QtWidgets.QAction(MainWin)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon18)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionExit.setFont(font)
        self.actionExit.setPriority(QtWidgets.QAction.HighPriority)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_DICOM = QtWidgets.QAction(MainWin)
        self.actionLoad_DICOM.setIcon(icon17)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionLoad_DICOM.setFont(font)
        self.actionLoad_DICOM.setObjectName("actionLoad_DICOM")
        self.toolBar.addAction(self.actionLoad_DICOM)
        self.toolBar.addAction(self.actionLoad_Image)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(3)
        self.comboBox_2DView.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWin.close)
        self.Slider_2D.valueChanged['int'].connect(self.sliceNum_sagittal.setNum)
        self.tableWidget_Patients.cellClicked['int','int'].connect(self.btn_LoadPatient.show)
        self.tableWidget_Patients.cellClicked['int','int'].connect(self.btn_DeletePatient.show)
        self.slider_threshold3D.valueChanged['int'].connect(self.lbl_threshold3D.setNum)
        self.slider_threshold3D_2.valueChanged['int'].connect(self.lbl_threshold3D_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "BronchoVision"))
        self.btn_NewPatient.setText(_translate("MainWin", "    New Patient ..."))
        self.groupBox_Patients.setTitle(_translate("MainWin", "Patients"))
        self.tableWidget_Patients.setSortingEnabled(True)
        item = self.tableWidget_Patients.horizontalHeaderItem(0)
        item.setText(_translate("MainWin", "Name"))
        item = self.tableWidget_Patients.horizontalHeaderItem(1)
        item.setText(_translate("MainWin", "Date"))
        self.btn_LoadPatient.setText(_translate("MainWin", " Load"))
        self.btn_DeletePatient.setText(_translate("MainWin", " Delete"))
        self.btn_ImportPatient.setText(_translate("MainWin", "Import Patient ..."))
        self.btn_ClearPatients.setText(_translate("MainWin", "Clear Patients"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_patients), _translate("MainWin", "Patients"))
        self.groupBox_Viewports.setTitle(_translate("MainWin", "Viewports"))
        self.label_2.setText(_translate("MainWin", "2D View"))
        self.comboBox_2DView.setCurrentText(_translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(0, _translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(1, _translate("MainWin", "Coronal"))
        self.comboBox_2DView.setItemText(2, _translate("MainWin", "Sagittal"))
        self.label_3.setText(_translate("MainWin", "3D Views Threshold:"))
        self.label_4.setText(_translate("MainWin", "Virtual"))
        self.lbl_threshold3D.setText(_translate("MainWin", "-600"))
        self.label_5.setText(_translate("MainWin", "Normal"))
        self.lbl_threshold3D_2.setText(_translate("MainWin", "-600"))
        self.btn_ResetViewports.setText(_translate("MainWin", "   Reset Viewports"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), _translate("MainWin", "View"))
        self.groupBox_segmentation.setTitle(_translate("MainWin", "Processing"))
        self.btn_Segment.setText(_translate("MainWin", "Segment Lung/Airways ..."))
        self.btn_Centerline.setText(_translate("MainWin", "Extract Centerline ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), _translate("MainWin", "Process"))
        self.btn_Connect.setText(_translate("MainWin", " Connect Tracker"))
        self.btn_ToolsWindow.setText(_translate("MainWin", " Tools Info ..."))
        self.btn_recordToolRef.setText(_translate("MainWin", " Start Record"))
        self.btn_registerCenterlines.setText(_translate("MainWin", " Register Centerlines ..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_online), _translate("MainWin", "Online"))
        self.btn_LoadRefPoints.setText(_translate("MainWin", "    Load Ref. Points ..."))
        self.btn_LoadPoints.setText(_translate("MainWin", "    Load Tool Points ..."))
        self.lbl_FrameNum.setText(_translate("MainWin", "0 of 0"))
        self.btn_playCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_pauseCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_stopCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.checkBox_showPoints.setText(_translate("MainWin", "Show Tracker Points"))
        self.btn_ResetVB.setText(_translate("MainWin", "   Reset Virtual Mode"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_offline), _translate("MainWin", "Offline"))
        self.btn_regMat.setText(_translate("MainWin", "Registration Matrix ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tracking), _translate("MainWin", "Tracking"))
        self.label_version.setText(_translate("MainWin", "2020-08 (Beta)  "))
        self.view1_desc.setText(_translate("MainWin", "Virtual"))
        self.view3_desc.setText(_translate("MainWin", "Bronchoscope"))
        self.sliceNum_sagittal.setText(_translate("MainWin", "50"))
        self.view4_title.setText(_translate("MainWin", "2D"))
        self.view2_desc.setText(_translate("MainWin", "Normal"))
        self.toolBar.setWindowTitle(_translate("MainWin", "toolBar"))
        self.actionLoad_Image.setText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setIconText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setToolTip(_translate("MainWin", "Load Single Medical Images"))
        self.actionExit.setText(_translate("MainWin", "    Exit           "))
        self.actionExit.setIconText(_translate("MainWin", "    Exit         "))
        self.actionExit.setToolTip(_translate("MainWin", "Exit Application"))
        self.actionLoad_DICOM.setText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setIconText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setToolTip(_translate("MainWin", "Load DICOM Series from Selected Directory"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec_())

