# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWin.resize(1462, 1032)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWin.sizePolicy().hasHeightForWidth())
        MainWin.setSizePolicy(sizePolicy)
        MainWin.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWin.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/BronchoVision.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWin.setWindowIcon(icon)
        MainWin.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWin.setAutoFillBackground(False)
        MainWin.setIconSize(QtCore.QSize(40, 40))
        MainWin.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setStyleSheet("")
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame_Left = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Left.sizePolicy().hasHeightForWidth())
        self.frame_Left.setSizePolicy(sizePolicy)
        self.frame_Left.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_Left.setAutoFillBackground(False)
        self.frame_Left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_Left.setLineWidth(1)
        self.frame_Left.setMidLineWidth(0)
        self.frame_Left.setObjectName("frame_Left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Left)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_Left)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(50, 50,50);\n"
"color: rgb(157, 205, 216);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_patients = QtWidgets.QWidget()
        self.tab_patients.setObjectName("tab_patients")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_patients)
        self.verticalLayout_11.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout_11.setSpacing(3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_NewPatient = QtWidgets.QToolButton(self.tab_patients)
        self.btn_NewPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_NewPatient.sizePolicy().hasHeightForWidth())
        self.btn_NewPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_NewPatient.setFont(font)
        self.btn_NewPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_NewPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_NewPatient.setAutoFillBackground(False)
        self.btn_NewPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/add_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_NewPatient.setIcon(icon1)
        self.btn_NewPatient.setIconSize(QtCore.QSize(40, 40))
        self.btn_NewPatient.setCheckable(False)
        self.btn_NewPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_NewPatient.setAutoRaise(True)
        self.btn_NewPatient.setObjectName("btn_NewPatient")
        self.verticalLayout_11.addWidget(self.btn_NewPatient)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem)
        self.groupBox_Patients = QtWidgets.QGroupBox(self.tab_patients)
        self.groupBox_Patients.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.groupBox_Patients.setFont(font)
        self.groupBox_Patients.setAutoFillBackground(False)
        self.groupBox_Patients.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Patients.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Patients.setFlat(False)
        self.groupBox_Patients.setCheckable(False)
        self.groupBox_Patients.setObjectName("groupBox_Patients")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_Patients)
        self.verticalLayout_12.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget_Patients = QtWidgets.QTableWidget(self.groupBox_Patients)
        self.tableWidget_Patients.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_Patients.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Patients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Patients.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget_Patients.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_Patients.setWordWrap(False)
        self.tableWidget_Patients.setRowCount(0)
        self.tableWidget_Patients.setObjectName("tableWidget_Patients")
        self.tableWidget_Patients.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Patients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Patients.setHorizontalHeaderItem(1, item)
        self.tableWidget_Patients.horizontalHeader().setVisible(False)
        self.tableWidget_Patients.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Patients.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_Patients.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Patients.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget_Patients.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Patients.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableWidget_Patients)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_15.setSpacing(7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_LoadPatient = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_LoadPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadPatient.sizePolicy().hasHeightForWidth())
        self.btn_LoadPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_LoadPatient.setFont(font)
        self.btn_LoadPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadPatient.setAutoFillBackground(False)
        self.btn_LoadPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/load_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadPatient.setIcon(icon2)
        self.btn_LoadPatient.setIconSize(QtCore.QSize(35, 35))
        self.btn_LoadPatient.setCheckable(False)
        self.btn_LoadPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadPatient.setAutoRaise(True)
        self.btn_LoadPatient.setObjectName("btn_LoadPatient")
        self.horizontalLayout_15.addWidget(self.btn_LoadPatient)
        self.btn_DeletePatient = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_DeletePatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_DeletePatient.sizePolicy().hasHeightForWidth())
        self.btn_DeletePatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_DeletePatient.setFont(font)
        self.btn_DeletePatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_DeletePatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_DeletePatient.setAutoFillBackground(False)
        self.btn_DeletePatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/delete_patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_DeletePatient.setIcon(icon3)
        self.btn_DeletePatient.setIconSize(QtCore.QSize(35, 35))
        self.btn_DeletePatient.setCheckable(False)
        self.btn_DeletePatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_DeletePatient.setAutoRaise(True)
        self.btn_DeletePatient.setObjectName("btn_DeletePatient")
        self.horizontalLayout_15.addWidget(self.btn_DeletePatient)
        self.horizontalLayout_15.setStretch(0, 2)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(7, 0, 7, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_ImportPatient = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_ImportPatient.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ImportPatient.sizePolicy().hasHeightForWidth())
        self.btn_ImportPatient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_ImportPatient.setFont(font)
        self.btn_ImportPatient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ImportPatient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ImportPatient.setAutoFillBackground(False)
        self.btn_ImportPatient.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_ImportPatient.setIconSize(QtCore.QSize(50, 50))
        self.btn_ImportPatient.setCheckable(False)
        self.btn_ImportPatient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ImportPatient.setAutoRaise(True)
        self.btn_ImportPatient.setObjectName("btn_ImportPatient")
        self.horizontalLayout_10.addWidget(self.btn_ImportPatient)
        self.btn_ClearPatients = QtWidgets.QToolButton(self.groupBox_Patients)
        self.btn_ClearPatients.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ClearPatients.sizePolicy().hasHeightForWidth())
        self.btn_ClearPatients.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_ClearPatients.setFont(font)
        self.btn_ClearPatients.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ClearPatients.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ClearPatients.setAutoFillBackground(False)
        self.btn_ClearPatients.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_ClearPatients.setIconSize(QtCore.QSize(50, 50))
        self.btn_ClearPatients.setCheckable(False)
        self.btn_ClearPatients.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ClearPatients.setAutoRaise(True)
        self.btn_ClearPatients.setObjectName("btn_ClearPatients")
        self.horizontalLayout_10.addWidget(self.btn_ClearPatients)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_11.addWidget(self.groupBox_Patients)
        self.tabWidget.addTab(self.tab_patients, "")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_14.setContentsMargins(5, 20, 5, 5)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_Viewports = QtWidgets.QGroupBox(self.tab_view)
        self.groupBox_Viewports.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.groupBox_Viewports.setFont(font)
        self.groupBox_Viewports.setAutoFillBackground(False)
        self.groupBox_Viewports.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Viewports.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Viewports.setFlat(False)
        self.groupBox_Viewports.setCheckable(False)
        self.groupBox_Viewports.setObjectName("groupBox_Viewports")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Viewports)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.comboBox_2DView = QtWidgets.QComboBox(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2DView.sizePolicy().hasHeightForWidth())
        self.comboBox_2DView.setSizePolicy(sizePolicy)
        self.comboBox_2DView.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.comboBox_2DView.setFont(font)
        self.comboBox_2DView.setAutoFillBackground(False)
        self.comboBox_2DView.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.comboBox_2DView.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_2DView.setFrame(False)
        self.comboBox_2DView.setObjectName("comboBox_2DView")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_2DView)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.slider_threshold3D = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D.setEnabled(False)
        self.slider_threshold3D.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.slider_threshold3D.setMinimum(-2000)
        self.slider_threshold3D.setMaximum(1000)
        self.slider_threshold3D.setSingleStep(10)
        self.slider_threshold3D.setPageStep(100)
        self.slider_threshold3D.setProperty("value", -600)
        self.slider_threshold3D.setTracking(False)
        self.slider_threshold3D.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D.setObjectName("slider_threshold3D")
        self.horizontalLayout_12.addWidget(self.slider_threshold3D)
        self.lbl_threshold3D = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D.setSizePolicy(sizePolicy)
        self.lbl_threshold3D.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.lbl_threshold3D.setFont(font)
        self.lbl_threshold3D.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D.setObjectName("lbl_threshold3D")
        self.horizontalLayout_12.addWidget(self.lbl_threshold3D)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Viewports)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.slider_threshold3D_2 = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D_2.setEnabled(False)
        self.slider_threshold3D_2.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.slider_threshold3D_2.setMinimum(-2000)
        self.slider_threshold3D_2.setMaximum(1000)
        self.slider_threshold3D_2.setSingleStep(10)
        self.slider_threshold3D_2.setPageStep(100)
        self.slider_threshold3D_2.setProperty("value", -600)
        self.slider_threshold3D_2.setTracking(False)
        self.slider_threshold3D_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D_2.setObjectName("slider_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.slider_threshold3D_2)
        self.lbl_threshold3D_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D_2.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D_2.setSizePolicy(sizePolicy)
        self.lbl_threshold3D_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.lbl_threshold3D_2.setFont(font)
        self.lbl_threshold3D_2.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D_2.setObjectName("lbl_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.lbl_threshold3D_2)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 2)
        self.horizontalLayout_14.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.btn_ResetViewports = QtWidgets.QToolButton(self.groupBox_Viewports)
        self.btn_ResetViewports.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetViewports.sizePolicy().hasHeightForWidth())
        self.btn_ResetViewports.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_ResetViewports.setFont(font)
        self.btn_ResetViewports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetViewports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetViewports.setAutoFillBackground(False)
        self.btn_ResetViewports.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/resetViews.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetViewports.setIcon(icon4)
        self.btn_ResetViewports.setIconSize(QtCore.QSize(50, 50))
        self.btn_ResetViewports.setCheckable(False)
        self.btn_ResetViewports.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetViewports.setAutoRaise(True)
        self.btn_ResetViewports.setObjectName("btn_ResetViewports")
        self.verticalLayout_5.addWidget(self.btn_ResetViewports)
        self.verticalLayout_14.addWidget(self.groupBox_Viewports)
        self.tabWidget.addTab(self.tab_view, "")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_process)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_segmentation = QtWidgets.QGroupBox(self.tab_process)
        self.groupBox_segmentation.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_segmentation.setFont(font)
        self.groupBox_segmentation.setAutoFillBackground(False)
        self.groupBox_segmentation.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_segmentation.setObjectName("groupBox_segmentation")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_segmentation)
        self.verticalLayout_13.setContentsMargins(-1, 7, -1, 7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_Segment = QtWidgets.QToolButton(self.groupBox_segmentation)
        self.btn_Segment.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Segment.sizePolicy().hasHeightForWidth())
        self.btn_Segment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Segment.setFont(font)
        self.btn_Segment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Segment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Segment.setAutoFillBackground(False)
        self.btn_Segment.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/Segmentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Segment.setIcon(icon5)
        self.btn_Segment.setIconSize(QtCore.QSize(50, 50))
        self.btn_Segment.setCheckable(False)
        self.btn_Segment.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Segment.setAutoRaise(True)
        self.btn_Segment.setObjectName("btn_Segment")
        self.verticalLayout_13.addWidget(self.btn_Segment)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.verticalLayout_6.addWidget(self.groupBox_segmentation)
        self.groupBox_registration = QtWidgets.QGroupBox(self.tab_process)
        self.groupBox_registration.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_registration.setFont(font)
        self.groupBox_registration.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_registration.setObjectName("groupBox_registration")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_registration)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_imageCenterline = QtWidgets.QFrame(self.groupBox_registration)
        self.frame_imageCenterline.setObjectName("frame_imageCenterline")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_imageCenterline)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_16.setSpacing(7)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label = QtWidgets.QLabel(self.frame_imageCenterline)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_16.addWidget(self.label)
        self.label_imageCenterline = QtWidgets.QLabel(self.frame_imageCenterline)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_imageCenterline.setFont(font)
        self.label_imageCenterline.setStyleSheet("color: rgb(255, 55, 120);")
        self.label_imageCenterline.setObjectName("label_imageCenterline")
        self.horizontalLayout_16.addWidget(self.label_imageCenterline)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.btn_extractCenterline = QtWidgets.QToolButton(self.frame_imageCenterline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_extractCenterline.sizePolicy().hasHeightForWidth())
        self.btn_extractCenterline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_extractCenterline.setFont(font)
        self.btn_extractCenterline.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_extractCenterline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_extractCenterline.setAutoFillBackground(False)
        self.btn_extractCenterline.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/centerLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_extractCenterline.setIcon(icon6)
        self.btn_extractCenterline.setIconSize(QtCore.QSize(50, 50))
        self.btn_extractCenterline.setCheckable(False)
        self.btn_extractCenterline.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_extractCenterline.setAutoRaise(True)
        self.btn_extractCenterline.setObjectName("btn_extractCenterline")
        self.verticalLayout_9.addWidget(self.btn_extractCenterline)
        self.btn_loadImageCenterline = QtWidgets.QToolButton(self.frame_imageCenterline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loadImageCenterline.sizePolicy().hasHeightForWidth())
        self.btn_loadImageCenterline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_loadImageCenterline.setFont(font)
        self.btn_loadImageCenterline.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_loadImageCenterline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_loadImageCenterline.setAutoFillBackground(False)
        self.btn_loadImageCenterline.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_loadImageCenterline.setIcon(icon7)
        self.btn_loadImageCenterline.setIconSize(QtCore.QSize(50, 50))
        self.btn_loadImageCenterline.setCheckable(False)
        self.btn_loadImageCenterline.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_loadImageCenterline.setAutoRaise(True)
        self.btn_loadImageCenterline.setObjectName("btn_loadImageCenterline")
        self.verticalLayout_9.addWidget(self.btn_loadImageCenterline)
        self.checkBox_showImageCenterline = QtWidgets.QCheckBox(self.frame_imageCenterline)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.checkBox_showImageCenterline.setFont(font)
        self.checkBox_showImageCenterline.setChecked(False)
        self.checkBox_showImageCenterline.setObjectName("checkBox_showImageCenterline")
        self.verticalLayout_9.addWidget(self.checkBox_showImageCenterline)
        self.verticalLayout_16.addWidget(self.frame_imageCenterline)
        self.label_7 = QtWidgets.QLabel(self.groupBox_registration)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icon/icons/arrow-down.png"))
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.frame_trackerCenterline = QtWidgets.QFrame(self.groupBox_registration)
        self.frame_trackerCenterline.setObjectName("frame_trackerCenterline")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_trackerCenterline)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.frame_trackerCenterline)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_17.addWidget(self.label_6)
        self.label_trackerCenterline = QtWidgets.QLabel(self.frame_trackerCenterline)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_trackerCenterline.setFont(font)
        self.label_trackerCenterline.setStyleSheet("color: rgb(255, 55, 120);")
        self.label_trackerCenterline.setObjectName("label_trackerCenterline")
        self.horizontalLayout_17.addWidget(self.label_trackerCenterline)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.btn_recordCoords = QtWidgets.QToolButton(self.frame_trackerCenterline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_recordCoords.sizePolicy().hasHeightForWidth())
        self.btn_recordCoords.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_recordCoords.setFont(font)
        self.btn_recordCoords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_recordCoords.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_recordCoords.setAutoFillBackground(False)
        self.btn_recordCoords.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"border-color: rgb(255, 78, 81);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/rec_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_recordCoords.setIcon(icon8)
        self.btn_recordCoords.setIconSize(QtCore.QSize(50, 50))
        self.btn_recordCoords.setCheckable(False)
        self.btn_recordCoords.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_recordCoords.setAutoRaise(True)
        self.btn_recordCoords.setObjectName("btn_recordCoords")
        self.verticalLayout_15.addWidget(self.btn_recordCoords)
        self.btn_loadtrackerCenterline = QtWidgets.QToolButton(self.frame_trackerCenterline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loadtrackerCenterline.sizePolicy().hasHeightForWidth())
        self.btn_loadtrackerCenterline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_loadtrackerCenterline.setFont(font)
        self.btn_loadtrackerCenterline.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_loadtrackerCenterline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_loadtrackerCenterline.setAutoFillBackground(False)
        self.btn_loadtrackerCenterline.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_loadtrackerCenterline.setIcon(icon7)
        self.btn_loadtrackerCenterline.setIconSize(QtCore.QSize(50, 50))
        self.btn_loadtrackerCenterline.setCheckable(False)
        self.btn_loadtrackerCenterline.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_loadtrackerCenterline.setAutoRaise(True)
        self.btn_loadtrackerCenterline.setObjectName("btn_loadtrackerCenterline")
        self.verticalLayout_15.addWidget(self.btn_loadtrackerCenterline)
        self.checkBox_showTrackerCenterline = QtWidgets.QCheckBox(self.frame_trackerCenterline)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.checkBox_showTrackerCenterline.setFont(font)
        self.checkBox_showTrackerCenterline.setChecked(False)
        self.checkBox_showTrackerCenterline.setObjectName("checkBox_showTrackerCenterline")
        self.verticalLayout_15.addWidget(self.checkBox_showTrackerCenterline)
        self.verticalLayout_16.addWidget(self.frame_trackerCenterline)
        self.label_8 = QtWidgets.QLabel(self.groupBox_registration)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icon/icons/arrow-down.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.frame = QtWidgets.QFrame(self.groupBox_registration)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_registerCenterlines = QtWidgets.QToolButton(self.frame)
        self.btn_registerCenterlines.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_registerCenterlines.sizePolicy().hasHeightForWidth())
        self.btn_registerCenterlines.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.btn_registerCenterlines.setFont(font)
        self.btn_registerCenterlines.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_registerCenterlines.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_registerCenterlines.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/register_centerlines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_registerCenterlines.setIcon(icon9)
        self.btn_registerCenterlines.setIconSize(QtCore.QSize(50, 50))
        self.btn_registerCenterlines.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_registerCenterlines.setAutoRaise(True)
        self.btn_registerCenterlines.setObjectName("btn_registerCenterlines")
        self.verticalLayout_7.addWidget(self.btn_registerCenterlines)
        self.verticalLayout_16.addWidget(self.frame)
        self.btn_regMat = QtWidgets.QToolButton(self.groupBox_registration)
        self.btn_regMat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_regMat.sizePolicy().hasHeightForWidth())
        self.btn_regMat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_regMat.setFont(font)
        self.btn_regMat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regMat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_regMat.setAutoFillBackground(False)
        self.btn_regMat.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/matrix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regMat.setIcon(icon10)
        self.btn_regMat.setIconSize(QtCore.QSize(50, 50))
        self.btn_regMat.setCheckable(False)
        self.btn_regMat.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_regMat.setAutoRaise(True)
        self.btn_regMat.setObjectName("btn_regMat")
        self.verticalLayout_16.addWidget(self.btn_regMat)
        self.frame_imageCenterline.raise_()
        self.frame_trackerCenterline.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.frame.raise_()
        self.btn_regMat.raise_()
        self.verticalLayout_6.addWidget(self.groupBox_registration)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.tabWidget.addTab(self.tab_process, "")
        self.tab_tracking = QtWidgets.QWidget()
        self.tab_tracking.setObjectName("tab_tracking")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_tracking)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_online = QtWidgets.QGroupBox(self.tab_tracking)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.groupBox_online.setFont(font)
        self.groupBox_online.setStyleSheet("")
        self.groupBox_online.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_online.setObjectName("groupBox_online")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_online)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Connect = QtWidgets.QToolButton(self.groupBox_online)
        self.btn_Connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Connect.sizePolicy().hasHeightForWidth())
        self.btn_Connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Connect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Connect.setAutoFillBackground(False)
        self.btn_Connect.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"selection-background-color: rgb(85, 85, 255);\n"
"alternate-background-color: rgb(85, 255, 127);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/tracker_disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Connect.setIcon(icon11)
        self.btn_Connect.setIconSize(QtCore.QSize(50, 50))
        self.btn_Connect.setCheckable(False)
        self.btn_Connect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Connect.setAutoRaise(True)
        self.btn_Connect.setObjectName("btn_Connect")
        self.verticalLayout_4.addWidget(self.btn_Connect)
        self.btn_ToolsWindow = QtWidgets.QToolButton(self.groupBox_online)
        self.btn_ToolsWindow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ToolsWindow.sizePolicy().hasHeightForWidth())
        self.btn_ToolsWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_ToolsWindow.setFont(font)
        self.btn_ToolsWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ToolsWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ToolsWindow.setAutoFillBackground(False)
        self.btn_ToolsWindow.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icons/Tools_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ToolsWindow.setIcon(icon12)
        self.btn_ToolsWindow.setIconSize(QtCore.QSize(50, 50))
        self.btn_ToolsWindow.setCheckable(False)
        self.btn_ToolsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ToolsWindow.setAutoRaise(True)
        self.btn_ToolsWindow.setObjectName("btn_ToolsWindow")
        self.verticalLayout_4.addWidget(self.btn_ToolsWindow)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.groupBox_online)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.groupBox_offline = QtWidgets.QGroupBox(self.tab_tracking)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_offline.sizePolicy().hasHeightForWidth())
        self.groupBox_offline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_offline.setFont(font)
        self.groupBox_offline.setAutoFillBackground(False)
        self.groupBox_offline.setStyleSheet("background-color: rgb(50, 50,50);")
        self.groupBox_offline.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_offline.setObjectName("groupBox_offline")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_offline)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LoadToolPoints = QtWidgets.QToolButton(self.groupBox_offline)
        self.btn_LoadToolPoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadToolPoints.sizePolicy().hasHeightForWidth())
        self.btn_LoadToolPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_LoadToolPoints.setFont(font)
        self.btn_LoadToolPoints.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadToolPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadToolPoints.setAutoFillBackground(False)
        self.btn_LoadToolPoints.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icons/trajectory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadToolPoints.setIcon(icon13)
        self.btn_LoadToolPoints.setIconSize(QtCore.QSize(50, 50))
        self.btn_LoadToolPoints.setCheckable(False)
        self.btn_LoadToolPoints.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadToolPoints.setAutoRaise(True)
        self.btn_LoadToolPoints.setObjectName("btn_LoadToolPoints")
        self.verticalLayout_3.addWidget(self.btn_LoadToolPoints)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.slider_Frames = QtWidgets.QSlider(self.groupBox_offline)
        self.slider_Frames.setEnabled(False)
        self.slider_Frames.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Frames.setObjectName("slider_Frames")
        self.horizontalLayout_13.addWidget(self.slider_Frames)
        self.lbl_FrameNum = QtWidgets.QLabel(self.groupBox_offline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FrameNum.sizePolicy().hasHeightForWidth())
        self.lbl_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.lbl_FrameNum.setFont(font)
        self.lbl_FrameNum.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_FrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FrameNum.setObjectName("lbl_FrameNum")
        self.horizontalLayout_13.addWidget(self.lbl_FrameNum)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_camButtons_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_camButtons_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_camButtons_3.setSpacing(0)
        self.horizontalLayout_camButtons_3.setObjectName("horizontalLayout_camButtons_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem10)
        self.btn_playCam = QtWidgets.QToolButton(self.groupBox_offline)
        self.btn_playCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_playCam.sizePolicy().hasHeightForWidth())
        self.btn_playCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playCam.setFont(font)
        self.btn_playCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_playCam.setAutoFillBackground(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_playCam.setIcon(icon14)
        self.btn_playCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_playCam.setAutoRaise(True)
        self.btn_playCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_playCam.setObjectName("btn_playCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_playCam)
        self.btn_pauseCam = QtWidgets.QToolButton(self.groupBox_offline)
        self.btn_pauseCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pauseCam.sizePolicy().hasHeightForWidth())
        self.btn_pauseCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pauseCam.setFont(font)
        self.btn_pauseCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pauseCam.setAutoFillBackground(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pauseCam.setIcon(icon15)
        self.btn_pauseCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_pauseCam.setAutoRaise(True)
        self.btn_pauseCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_pauseCam.setObjectName("btn_pauseCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_pauseCam)
        self.btn_stopCam = QtWidgets.QToolButton(self.groupBox_offline)
        self.btn_stopCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stopCam.sizePolicy().hasHeightForWidth())
        self.btn_stopCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stopCam.setFont(font)
        self.btn_stopCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stopCam.setAutoFillBackground(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stopCam.setIcon(icon16)
        self.btn_stopCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_stopCam.setAutoRaise(True)
        self.btn_stopCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_stopCam.setObjectName("btn_stopCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_stopCam)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_camButtons_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.checkBox_showPoints = QtWidgets.QCheckBox(self.groupBox_offline)
        self.checkBox_showPoints.setEnabled(False)
        font = QtGui.QFont()
        font.setKerning(False)
        self.checkBox_showPoints.setFont(font)
        self.checkBox_showPoints.setChecked(False)
        self.checkBox_showPoints.setObjectName("checkBox_showPoints")
        self.verticalLayout_3.addWidget(self.checkBox_showPoints)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.btn_ResetVB = QtWidgets.QToolButton(self.groupBox_offline)
        self.btn_ResetVB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetVB.sizePolicy().hasHeightForWidth())
        self.btn_ResetVB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_ResetVB.setFont(font)
        self.btn_ResetVB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetVB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetVB.setAutoFillBackground(False)
        self.btn_ResetVB.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetVB.setIcon(icon17)
        self.btn_ResetVB.setIconSize(QtCore.QSize(50, 50))
        self.btn_ResetVB.setCheckable(False)
        self.btn_ResetVB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetVB.setAutoRaise(True)
        self.btn_ResetVB.setObjectName("btn_ResetVB")
        self.verticalLayout_3.addWidget(self.btn_ResetVB)
        self.verticalLayout_2.addWidget(self.groupBox_offline)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.tabWidget.addTab(self.tab_tracking, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_Logo = QtWidgets.QLabel(self.frame_Left)
        self.label_Logo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Logo.sizePolicy().hasHeightForWidth())
        self.label_Logo.setSizePolicy(sizePolicy)
        self.label_Logo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setKerning(False)
        self.label_Logo.setFont(font)
        self.label_Logo.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_Logo.setLineWidth(0)
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap(":/logo/logo/logo_transparent.png"))
        self.label_Logo.setScaledContents(True)
        self.label_Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Logo.setObjectName("label_Logo")
        self.verticalLayout.addWidget(self.label_Logo)
        self.label_version = QtWidgets.QLabel(self.frame_Left)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(157, 205, 216);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.verticalLayout.addWidget(self.label_version)
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.layout_noView = QtWidgets.QWidget()
        self.layout_noView.setObjectName("layout_noView")
        self.stackedWidget.addWidget(self.layout_noView)
        self.layout_2x2 = QtWidgets.QWidget()
        self.layout_2x2.setObjectName("layout_2x2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layout_2x2)
        self.verticalLayout_17.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_17.setSpacing(3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_Viewports = QtWidgets.QFrame(self.layout_2x2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewports.sizePolicy().hasHeightForWidth())
        self.frame_Viewports.setSizePolicy(sizePolicy)
        self.frame_Viewports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewports.setObjectName("frame_Viewports")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Viewports)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_lowerLeft = QtWidgets.QVBoxLayout()
        self.verticalLayout_lowerLeft.setSpacing(0)
        self.verticalLayout_lowerLeft.setObjectName("verticalLayout_lowerLeft")
        self.vtk_panel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_endoscope.sizePolicy().hasHeightForWidth())
        self.vtk_panel_endoscope.setSizePolicy(sizePolicy)
        self.vtk_panel_endoscope.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_endoscope.setLineWidth(0)
        self.vtk_panel_endoscope.setObjectName("vtk_panel_endoscope")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.vtk_panel_endoscope)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.vtk_panel_endoscope)
        self.label_9.setStyleSheet("background-color: rgba(0, 0, 0, 25);\n"
"image: url(:/icon/icons/bronchs_transparent.png);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.label_bronchoscopeStatus = QtWidgets.QLabel(self.vtk_panel_endoscope)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_bronchoscopeStatus.setFont(font)
        self.label_bronchoscopeStatus.setStyleSheet("color: rgb(255, 145, 71);\n"
"background-color: rgb(0, 0, 0);")
        self.label_bronchoscopeStatus.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_bronchoscopeStatus.setObjectName("label_bronchoscopeStatus")
        self.verticalLayout_10.addWidget(self.label_bronchoscopeStatus)
        self.verticalLayout_10.setStretch(0, 20)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_lowerLeft.addWidget(self.vtk_panel_endoscope)
        self.SubPanel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_endoscope.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_endoscope.sizePolicy().hasHeightForWidth())
        self.SubPanel_endoscope.setSizePolicy(sizePolicy)
        self.SubPanel_endoscope.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SubPanel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_endoscope.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_endoscope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_endoscope.setObjectName("SubPanel_endoscope")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SubPanel_endoscope)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.view3_desc = QtWidgets.QLabel(self.SubPanel_endoscope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3_desc.sizePolicy().hasHeightForWidth())
        self.view3_desc.setSizePolicy(sizePolicy)
        self.view3_desc.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.view3_desc.setFont(font)
        self.view3_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view3_desc.setObjectName("view3_desc")
        self.horizontalLayout_4.addWidget(self.view3_desc)
        spacerItem14 = QtWidgets.QSpacerItem(395, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.btn_maximize_Bronchoscope = QtWidgets.QToolButton(self.SubPanel_endoscope)
        self.btn_maximize_Bronchoscope.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_maximize_Bronchoscope.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/icons/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_Bronchoscope.setIcon(icon18)
        self.btn_maximize_Bronchoscope.setIconSize(QtCore.QSize(30, 30))
        self.btn_maximize_Bronchoscope.setAutoRaise(True)
        self.btn_maximize_Bronchoscope.setArrowType(QtCore.Qt.NoArrow)
        self.btn_maximize_Bronchoscope.setObjectName("btn_maximize_Bronchoscope")
        self.horizontalLayout_4.addWidget(self.btn_maximize_Bronchoscope)
        self.verticalLayout_lowerLeft.addWidget(self.SubPanel_endoscope)
        self.verticalLayout_lowerLeft.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_lowerLeft, 1, 0, 1, 1)
        self.verticalLayout_upperLeft = QtWidgets.QVBoxLayout()
        self.verticalLayout_upperLeft.setSpacing(0)
        self.verticalLayout_upperLeft.setObjectName("verticalLayout_upperLeft")
        self.vtk_panel_3D_1 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_1.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_1.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_1.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 141, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.vtk_panel_3D_1.setPalette(palette)
        font = QtGui.QFont()
        font.setKerning(False)
        self.vtk_panel_3D_1.setFont(font)
        self.vtk_panel_3D_1.setAutoFillBackground(False)
        self.vtk_panel_3D_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_1.setLineWidth(0)
        self.vtk_panel_3D_1.setObjectName("vtk_panel_3D_1")
        self.verticalLayout_upperLeft.addWidget(self.vtk_panel_3D_1)
        self.SubPanel_3D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D.setEnabled(True)
        self.SubPanel_3D.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SubPanel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D.setObjectName("SubPanel_3D")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.SubPanel_3D)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.view1_desc = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view1_desc.sizePolicy().hasHeightForWidth())
        self.view1_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.view1_desc.setFont(font)
        self.view1_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view1_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.view1_desc.setObjectName("view1_desc")
        self.horizontalLayout_5.addWidget(self.view1_desc)
        spacerItem15 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.btn_maximize_3D = QtWidgets.QToolButton(self.SubPanel_3D)
        self.btn_maximize_3D.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_maximize_3D.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximize_3D.setIcon(icon18)
        self.btn_maximize_3D.setIconSize(QtCore.QSize(30, 30))
        self.btn_maximize_3D.setAutoRaise(True)
        self.btn_maximize_3D.setArrowType(QtCore.Qt.NoArrow)
        self.btn_maximize_3D.setObjectName("btn_maximize_3D")
        self.horizontalLayout_5.addWidget(self.btn_maximize_3D)
        self.verticalLayout_upperLeft.addWidget(self.SubPanel_3D)
        self.verticalLayout_upperLeft.setStretch(0, 20)
        self.verticalLayout_upperLeft.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_upperLeft, 0, 0, 1, 1)
        self.verticalLayout_lowerRight = QtWidgets.QVBoxLayout()
        self.verticalLayout_lowerRight.setSpacing(0)
        self.verticalLayout_lowerRight.setObjectName("verticalLayout_lowerRight")
        self.vtk_panel_2D = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_2D.sizePolicy().hasHeightForWidth())
        self.vtk_panel_2D.setSizePolicy(sizePolicy)
        self.vtk_panel_2D.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(False)
        self.vtk_panel_2D.setFont(font)
        self.vtk_panel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_2D.setLineWidth(0)
        self.vtk_panel_2D.setObjectName("vtk_panel_2D")
        self.verticalLayout_lowerRight.addWidget(self.vtk_panel_2D)
        self.SubPanel_2D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_2D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_2D.sizePolicy().hasHeightForWidth())
        self.SubPanel_2D.setSizePolicy(sizePolicy)
        self.SubPanel_2D.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SubPanel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_2D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_2D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_2D.setObjectName("SubPanel_2D")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SubPanel_2D)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sliceNum_sagittal = QtWidgets.QLabel(self.SubPanel_2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_sagittal.sizePolicy().hasHeightForWidth())
        self.sliceNum_sagittal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.sliceNum_sagittal.setFont(font)
        self.sliceNum_sagittal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_sagittal.setObjectName("sliceNum_sagittal")
        self.horizontalLayout_3.addWidget(self.sliceNum_sagittal)
        self.Slider_2D = QtWidgets.QSlider(self.SubPanel_2D)
        self.Slider_2D.setAutoFillBackground(False)
        self.Slider_2D.setStyleSheet("")
        self.Slider_2D.setProperty("value", 50)
        self.Slider_2D.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2D.setObjectName("Slider_2D")
        self.horizontalLayout_3.addWidget(self.Slider_2D)
        self.btn_maximize_2D = QtWidgets.QToolButton(self.SubPanel_2D)
        self.btn_maximize_2D.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_maximize_2D.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximize_2D.setIcon(icon18)
        self.btn_maximize_2D.setIconSize(QtCore.QSize(30, 30))
        self.btn_maximize_2D.setAutoRaise(True)
        self.btn_maximize_2D.setArrowType(QtCore.Qt.NoArrow)
        self.btn_maximize_2D.setObjectName("btn_maximize_2D")
        self.horizontalLayout_3.addWidget(self.btn_maximize_2D)
        self.verticalLayout_lowerRight.addWidget(self.SubPanel_2D)
        self.verticalLayout_lowerRight.setStretch(0, 20)
        self.verticalLayout_lowerRight.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_lowerRight, 1, 1, 1, 1)
        self.verticalLayout_upperRight = QtWidgets.QVBoxLayout()
        self.verticalLayout_upperRight.setSpacing(0)
        self.verticalLayout_upperRight.setObjectName("verticalLayout_upperRight")
        self.vtk_panel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_2.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_2.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(False)
        self.vtk_panel_3D_2.setFont(font)
        self.vtk_panel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_2.setLineWidth(0)
        self.vtk_panel_3D_2.setObjectName("vtk_panel_3D_2")
        self.verticalLayout_upperRight.addWidget(self.vtk_panel_3D_2)
        self.SubPanel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D_2.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D_2.setSizePolicy(sizePolicy)
        self.SubPanel_3D_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SubPanel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D_2.setObjectName("SubPanel_3D_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SubPanel_3D_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view2_desc = QtWidgets.QLabel(self.SubPanel_3D_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2_desc.sizePolicy().hasHeightForWidth())
        self.view2_desc.setSizePolicy(sizePolicy)
        self.view2_desc.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.view2_desc.setFont(font)
        self.view2_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view2_desc.setObjectName("view2_desc")
        self.horizontalLayout_2.addWidget(self.view2_desc)
        spacerItem16 = QtWidgets.QSpacerItem(384, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.btn_maximize_3D_2 = QtWidgets.QToolButton(self.SubPanel_3D_2)
        self.btn_maximize_3D_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_maximize_3D_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximize_3D_2.setIcon(icon18)
        self.btn_maximize_3D_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_maximize_3D_2.setAutoRaise(True)
        self.btn_maximize_3D_2.setArrowType(QtCore.Qt.NoArrow)
        self.btn_maximize_3D_2.setObjectName("btn_maximize_3D_2")
        self.horizontalLayout_2.addWidget(self.btn_maximize_3D_2)
        self.verticalLayout_upperRight.addWidget(self.SubPanel_3D_2)
        self.verticalLayout_upperRight.setStretch(0, 20)
        self.verticalLayout_upperRight.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_upperRight, 0, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_Viewports)
        self.stackedWidget.addWidget(self.layout_2x2)
        self.layout_3D = QtWidgets.QWidget()
        self.layout_3D.setObjectName("layout_3D")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layout_3D)
        self.verticalLayout_19.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_19.setSpacing(3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_Viewport_max = QtWidgets.QFrame(self.layout_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewport_max.sizePolicy().hasHeightForWidth())
        self.frame_Viewport_max.setSizePolicy(sizePolicy)
        self.frame_Viewport_max.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewport_max.setObjectName("frame_Viewport_max")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_Viewport_max)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3D_max = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D_max.setSpacing(0)
        self.verticalLayout_3D_max.setObjectName("verticalLayout_3D_max")
        self.vtk_panel_3D_max = QtWidgets.QFrame(self.frame_Viewport_max)
        self.vtk_panel_3D_max.setMinimumSize(QtCore.QSize(1000, 500))
        self.vtk_panel_3D_max.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_max.setLineWidth(0)
        self.vtk_panel_3D_max.setObjectName("vtk_panel_3D_max")
        self.verticalLayout_3D_max.addWidget(self.vtk_panel_3D_max)
        self.SubPanel_3D_max = QtWidgets.QFrame(self.frame_Viewport_max)
        self.SubPanel_3D_max.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D_max.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D_max.setSizePolicy(sizePolicy)
        self.SubPanel_3D_max.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D_max.setAutoFillBackground(False)
        self.SubPanel_3D_max.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D_max.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D_max.setObjectName("SubPanel_3D_max")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.SubPanel_3D_max)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.view_desc_max = QtWidgets.QLabel(self.SubPanel_3D_max)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_desc_max.sizePolicy().hasHeightForWidth())
        self.view_desc_max.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.view_desc_max.setFont(font)
        self.view_desc_max.setStyleSheet("color: rgb(157, 205, 216);")
        self.view_desc_max.setObjectName("view_desc_max")
        self.horizontalLayout_25.addWidget(self.view_desc_max)
        self.horizontalLayout_25.setStretch(0, 2)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.verticalLayout_3D_max.addWidget(self.SubPanel_3D_max)
        self.verticalLayout_3D_max.setStretch(0, 20)
        self.verticalLayout_3D_max.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_3D_max, 0, 0, 1, 1)
        self.verticalLayout_19.addWidget(self.frame_Viewport_max)
        self.stackedWidget.addWidget(self.layout_3D)
        self.horizontalLayout.addWidget(self.splitter)
        MainWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(False)
        self.toolBar.setFont(font)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setMouseTracking(False)
        self.toolBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setStyleSheet("color: rgb(98, 185, 189);")
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Image = QtWidgets.QAction(MainWin)
        self.actionLoad_Image.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.actionLoad_Image.setFont(font)
        self.actionLoad_Image.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionLoad_Image.setIconVisibleInMenu(True)
        self.actionLoad_Image.setProperty("shortcutVisibleInContextMenu", False)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionExit = QtWidgets.QAction(MainWin)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon19)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.actionExit.setFont(font)
        self.actionExit.setPriority(QtWidgets.QAction.HighPriority)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_DICOM = QtWidgets.QAction(MainWin)
        self.actionLoad_DICOM.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.actionLoad_DICOM.setFont(font)
        self.actionLoad_DICOM.setObjectName("actionLoad_DICOM")
        self.toolBar.addAction(self.actionLoad_DICOM)
        self.toolBar.addAction(self.actionLoad_Image)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_2DView.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        self.actionExit.triggered.connect(MainWin.close)
        self.tableWidget_Patients.cellClicked['int','int'].connect(self.btn_DeletePatient.show)
        self.slider_threshold3D.valueChanged['int'].connect(self.lbl_threshold3D.setNum)
        self.slider_threshold3D_2.valueChanged['int'].connect(self.lbl_threshold3D_2.setNum)
        self.tableWidget_Patients.cellClicked['int','int'].connect(self.btn_LoadPatient.show)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "BronchoVision"))
        self.btn_NewPatient.setText(_translate("MainWin", "    New Patient ..."))
        self.groupBox_Patients.setTitle(_translate("MainWin", "Patients"))
        self.tableWidget_Patients.setSortingEnabled(True)
        item = self.tableWidget_Patients.horizontalHeaderItem(0)
        item.setText(_translate("MainWin", "Name"))
        item = self.tableWidget_Patients.horizontalHeaderItem(1)
        item.setText(_translate("MainWin", "Date"))
        self.btn_LoadPatient.setText(_translate("MainWin", " Load"))
        self.btn_DeletePatient.setText(_translate("MainWin", " Delete"))
        self.btn_ImportPatient.setText(_translate("MainWin", "Import Patient ..."))
        self.btn_ClearPatients.setText(_translate("MainWin", "Clear Patients"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_patients), _translate("MainWin", "Patient"))
        self.groupBox_Viewports.setTitle(_translate("MainWin", "Viewports"))
        self.label_2.setText(_translate("MainWin", "2D View"))
        self.comboBox_2DView.setCurrentText(_translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(0, _translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(1, _translate("MainWin", "Coronal"))
        self.comboBox_2DView.setItemText(2, _translate("MainWin", "Sagittal"))
        self.label_3.setText(_translate("MainWin", "3D Views Threshold:"))
        self.label_4.setText(_translate("MainWin", "Virtual"))
        self.lbl_threshold3D.setText(_translate("MainWin", "-600"))
        self.label_5.setText(_translate("MainWin", "Normal"))
        self.lbl_threshold3D_2.setText(_translate("MainWin", "-600"))
        self.btn_ResetViewports.setText(_translate("MainWin", "   Reset Viewports"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), _translate("MainWin", "View"))
        self.groupBox_segmentation.setTitle(_translate("MainWin", "Segmentation"))
        self.btn_Segment.setText(_translate("MainWin", "Segment Lung/Airways ..."))
        self.groupBox_registration.setTitle(_translate("MainWin", "Registration"))
        self.label.setText(_translate("MainWin", "• Image Centerline :"))
        self.label_imageCenterline.setText(_translate("MainWin", "Not Available"))
        self.btn_extractCenterline.setText(_translate("MainWin", "Extract ..."))
        self.btn_loadImageCenterline.setText(_translate("MainWin", " Load ..."))
        self.checkBox_showImageCenterline.setText(_translate("MainWin", "Show Image Centerline"))
        self.label_6.setText(_translate("MainWin", "• Tracker Centerline :"))
        self.label_trackerCenterline.setText(_translate("MainWin", "Not Available"))
        self.btn_recordCoords.setText(_translate("MainWin", " Start Record"))
        self.btn_loadtrackerCenterline.setText(_translate("MainWin", " Load ..."))
        self.checkBox_showTrackerCenterline.setText(_translate("MainWin", "Show Tracker Centerline"))
        self.btn_registerCenterlines.setText(_translate("MainWin", " Register Centerlines ..."))
        self.btn_regMat.setText(_translate("MainWin", "Registration Matrix ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), _translate("MainWin", "Prep."))
        self.groupBox_online.setTitle(_translate("MainWin", "Online"))
        self.btn_Connect.setText(_translate("MainWin", " Connect Tracker"))
        self.btn_ToolsWindow.setText(_translate("MainWin", " Tools Info ..."))
        self.groupBox_offline.setTitle(_translate("MainWin", "Offline"))
        self.btn_LoadToolPoints.setText(_translate("MainWin", "    Load Tool Points ..."))
        self.lbl_FrameNum.setText(_translate("MainWin", "0 of 0"))
        self.btn_playCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_pauseCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_stopCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.checkBox_showPoints.setText(_translate("MainWin", "Show Tracker Points"))
        self.btn_ResetVB.setText(_translate("MainWin", "   Reset Virtual Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tracking), _translate("MainWin", "Track"))
        self.label_version.setText(_translate("MainWin", "2020-12 (Phantom Version)  "))
        self.label_bronchoscopeStatus.setText(_translate("MainWin", "Ø Bronchoscope is Not Available Ø"))
        self.view3_desc.setText(_translate("MainWin", "Bronchoscope"))
        self.btn_maximize_Bronchoscope.setText(_translate("MainWin", "Maximize View"))
        self.view1_desc.setText(_translate("MainWin", "Virtual"))
        self.btn_maximize_3D.setText(_translate("MainWin", "Maximize View"))
        self.sliceNum_sagittal.setText(_translate("MainWin", "50"))
        self.btn_maximize_2D.setText(_translate("MainWin", "Maximize View"))
        self.view2_desc.setText(_translate("MainWin", "Normal"))
        self.btn_maximize_3D_2.setText(_translate("MainWin", "Maximize View"))
        self.view_desc_max.setText(_translate("MainWin", "Normal"))
        self.toolBar.setWindowTitle(_translate("MainWin", "toolBar"))
        self.actionLoad_Image.setText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setIconText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setToolTip(_translate("MainWin", "Load Single Medical Images"))
        self.actionExit.setText(_translate("MainWin", "    Exit           "))
        self.actionExit.setIconText(_translate("MainWin", "    Exit         "))
        self.actionExit.setToolTip(_translate("MainWin", "Exit Application"))
        self.actionLoad_DICOM.setText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setIconText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setToolTip(_translate("MainWin", "Load DICOM Series from Selected Directory"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec_())

