# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1278, 629)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame_Left = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Left.sizePolicy().hasHeightForWidth())
        self.frame_Left.setSizePolicy(sizePolicy)
        self.frame_Left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_Left.setAutoFillBackground(True)
        self.frame_Left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_Left.setLineWidth(1)
        self.frame_Left.setMidLineWidth(0)
        self.frame_Left.setObjectName("frame_Left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Left)
        self.verticalLayout.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_VB = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_VB.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_VB.setFont(font)
        self.groupBox_VB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_VB.setAutoFillBackground(False)
        self.groupBox_VB.setStyleSheet("color: rgb(157, 205, 216);\n"
"border-color: rgb(114, 171, 171);")
        self.groupBox_VB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_VB.setFlat(True)
        self.groupBox_VB.setCheckable(False)
        self.groupBox_VB.setObjectName("groupBox_VB")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_VB)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LoadPoints = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_LoadPoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadPoints.sizePolicy().hasHeightForWidth())
        self.btn_LoadPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_LoadPoints.setFont(font)
        self.btn_LoadPoints.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadPoints.setAutoFillBackground(False)
        self.btn_LoadPoints.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/trajectory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadPoints.setIcon(icon)
        self.btn_LoadPoints.setIconSize(QtCore.QSize(36, 36))
        self.btn_LoadPoints.setCheckable(False)
        self.btn_LoadPoints.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadPoints.setAutoRaise(True)
        self.btn_LoadPoints.setObjectName("btn_LoadPoints")
        self.verticalLayout_3.addWidget(self.btn_LoadPoints)
        self.checkBox_showPoints = QtWidgets.QCheckBox(self.groupBox_VB)
        self.checkBox_showPoints.setEnabled(False)
        self.checkBox_showPoints.setChecked(True)
        self.checkBox_showPoints.setObjectName("checkBox_showPoints")
        self.verticalLayout_3.addWidget(self.checkBox_showPoints)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.slider_Frames = QtWidgets.QSlider(self.groupBox_VB)
        self.slider_Frames.setEnabled(False)
        self.slider_Frames.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Frames.setObjectName("slider_Frames")
        self.horizontalLayout_10.addWidget(self.slider_Frames)
        self.lbl_FrameNum = QtWidgets.QLabel(self.groupBox_VB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FrameNum.sizePolicy().hasHeightForWidth())
        self.lbl_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_FrameNum.setFont(font)
        self.lbl_FrameNum.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_FrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FrameNum.setObjectName("lbl_FrameNum")
        self.horizontalLayout_10.addWidget(self.lbl_FrameNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_camButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_camButtons.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_camButtons.setSpacing(0)
        self.horizontalLayout_camButtons.setObjectName("horizontalLayout_camButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons.addItem(spacerItem)
        self.btn_playCam = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_playCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_playCam.sizePolicy().hasHeightForWidth())
        self.btn_playCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playCam.setFont(font)
        self.btn_playCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_playCam.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_playCam.setIcon(icon1)
        self.btn_playCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_playCam.setAutoRaise(True)
        self.btn_playCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_playCam.setObjectName("btn_playCam")
        self.horizontalLayout_camButtons.addWidget(self.btn_playCam)
        self.btn_pauseCam = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_pauseCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pauseCam.sizePolicy().hasHeightForWidth())
        self.btn_pauseCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pauseCam.setFont(font)
        self.btn_pauseCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pauseCam.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pauseCam.setIcon(icon2)
        self.btn_pauseCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_pauseCam.setAutoRaise(True)
        self.btn_pauseCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_pauseCam.setObjectName("btn_pauseCam")
        self.horizontalLayout_camButtons.addWidget(self.btn_pauseCam)
        self.btn_stopCam = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_stopCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stopCam.sizePolicy().hasHeightForWidth())
        self.btn_stopCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stopCam.setFont(font)
        self.btn_stopCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stopCam.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stopCam.setIcon(icon3)
        self.btn_stopCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_stopCam.setAutoRaise(True)
        self.btn_stopCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_stopCam.setObjectName("btn_stopCam")
        self.horizontalLayout_camButtons.addWidget(self.btn_stopCam)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_camButtons)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.btn_ResetVB = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_ResetVB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetVB.sizePolicy().hasHeightForWidth())
        self.btn_ResetVB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetVB.setFont(font)
        self.btn_ResetVB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetVB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetVB.setAutoFillBackground(False)
        self.btn_ResetVB.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetVB.setIcon(icon4)
        self.btn_ResetVB.setIconSize(QtCore.QSize(36, 36))
        self.btn_ResetVB.setCheckable(False)
        self.btn_ResetVB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetVB.setAutoRaise(True)
        self.btn_ResetVB.setObjectName("btn_ResetVB")
        self.verticalLayout_3.addWidget(self.btn_ResetVB)
        self.verticalLayout.addWidget(self.groupBox_VB)
        self.groupBox_Tracker = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_Tracker.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Tracker.setFont(font)
        self.groupBox_Tracker.setAutoFillBackground(False)
        self.groupBox_Tracker.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Tracker.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Tracker.setFlat(True)
        self.groupBox_Tracker.setCheckable(False)
        self.groupBox_Tracker.setObjectName("groupBox_Tracker")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Tracker)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Connect = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_Connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Connect.sizePolicy().hasHeightForWidth())
        self.btn_Connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Connect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Connect.setAutoFillBackground(False)
        self.btn_Connect.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_Connect.setIcon(icon4)
        self.btn_Connect.setIconSize(QtCore.QSize(36, 36))
        self.btn_Connect.setCheckable(False)
        self.btn_Connect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Connect.setAutoRaise(True)
        self.btn_Connect.setObjectName("btn_Connect")
        self.verticalLayout_4.addWidget(self.btn_Connect)
        self.btn_ToolsWindow = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_ToolsWindow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ToolsWindow.sizePolicy().hasHeightForWidth())
        self.btn_ToolsWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ToolsWindow.setFont(font)
        self.btn_ToolsWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ToolsWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ToolsWindow.setAutoFillBackground(False)
        self.btn_ToolsWindow.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/Tools_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ToolsWindow.setIcon(icon5)
        self.btn_ToolsWindow.setIconSize(QtCore.QSize(36, 36))
        self.btn_ToolsWindow.setCheckable(False)
        self.btn_ToolsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ToolsWindow.setAutoRaise(True)
        self.btn_ToolsWindow.setObjectName("btn_ToolsWindow")
        self.verticalLayout_4.addWidget(self.btn_ToolsWindow)
        self.verticalLayout.addWidget(self.groupBox_Tracker)
        self.groupBox_Viewports = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_Viewports.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Viewports.setFont(font)
        self.groupBox_Viewports.setAutoFillBackground(False)
        self.groupBox_Viewports.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Viewports.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Viewports.setFlat(True)
        self.groupBox_Viewports.setCheckable(False)
        self.groupBox_Viewports.setObjectName("groupBox_Viewports")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Viewports)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_ResetViewports = QtWidgets.QToolButton(self.groupBox_Viewports)
        self.btn_ResetViewports.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetViewports.sizePolicy().hasHeightForWidth())
        self.btn_ResetViewports.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetViewports.setFont(font)
        self.btn_ResetViewports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetViewports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetViewports.setAutoFillBackground(False)
        self.btn_ResetViewports.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/resetViews.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetViewports.setIcon(icon6)
        self.btn_ResetViewports.setIconSize(QtCore.QSize(36, 36))
        self.btn_ResetViewports.setCheckable(False)
        self.btn_ResetViewports.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetViewports.setAutoRaise(True)
        self.btn_ResetViewports.setObjectName("btn_ResetViewports")
        self.verticalLayout_5.addWidget(self.btn_ResetViewports)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_Viewports)
        self.label = QtWidgets.QLabel(self.frame_Left)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(250, 30))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo/logo_transparent.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 1)
        self.frame_Viewports = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewports.sizePolicy().hasHeightForWidth())
        self.frame_Viewports.setSizePolicy(sizePolicy)
        self.frame_Viewports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewports.setObjectName("frame_Viewports")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Viewports)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_axial = QtWidgets.QVBoxLayout()
        self.verticalLayout_axial.setSpacing(0)
        self.verticalLayout_axial.setObjectName("verticalLayout_axial")
        self.vtk_panel_axial = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_axial.sizePolicy().hasHeightForWidth())
        self.vtk_panel_axial.setSizePolicy(sizePolicy)
        self.vtk_panel_axial.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_axial.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_axial.setLineWidth(0)
        self.vtk_panel_axial.setObjectName("vtk_panel_axial")
        self.verticalLayout_axial.addWidget(self.vtk_panel_axial)
        self.SubPanel_axial = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_axial.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_axial.sizePolicy().hasHeightForWidth())
        self.SubPanel_axial.setSizePolicy(sizePolicy)
        self.SubPanel_axial.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_axial.setAutoFillBackground(False)
        self.SubPanel_axial.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_axial.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_axial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_axial.setObjectName("SubPanel_axial")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.SubPanel_axial)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Slider_axial = QtWidgets.QSlider(self.SubPanel_axial)
        self.Slider_axial.setAutoFillBackground(False)
        self.Slider_axial.setStyleSheet("")
        self.Slider_axial.setProperty("value", 50)
        self.Slider_axial.setTracking(True)
        self.Slider_axial.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_axial.setInvertedAppearance(False)
        self.Slider_axial.setInvertedControls(False)
        self.Slider_axial.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_axial.setObjectName("Slider_axial")
        self.horizontalLayout_2.addWidget(self.Slider_axial)
        self.sliceNum_axial = QtWidgets.QLabel(self.SubPanel_axial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial.setFont(font)
        self.sliceNum_axial.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial.setObjectName("sliceNum_axial")
        self.horizontalLayout_2.addWidget(self.sliceNum_axial)
        self.sliceNum_axial_2 = QtWidgets.QLabel(self.SubPanel_axial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_2.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_2.setFont(font)
        self.sliceNum_axial_2.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_2.setObjectName("sliceNum_axial_2")
        self.horizontalLayout_2.addWidget(self.sliceNum_axial_2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_axial.addWidget(self.SubPanel_axial)
        self.verticalLayout_axial.setStretch(0, 20)
        self.verticalLayout_axial.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_axial, 0, 1, 1, 1)
        self.verticalLayout_sagittal = QtWidgets.QVBoxLayout()
        self.verticalLayout_sagittal.setSpacing(0)
        self.verticalLayout_sagittal.setObjectName("verticalLayout_sagittal")
        self.vtk_panel_sagittal = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_sagittal.sizePolicy().hasHeightForWidth())
        self.vtk_panel_sagittal.setSizePolicy(sizePolicy)
        self.vtk_panel_sagittal.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_sagittal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_sagittal.setLineWidth(0)
        self.vtk_panel_sagittal.setObjectName("vtk_panel_sagittal")
        self.verticalLayout_sagittal.addWidget(self.vtk_panel_sagittal)
        self.SubPanel_sagittal = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_sagittal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_sagittal.sizePolicy().hasHeightForWidth())
        self.SubPanel_sagittal.setSizePolicy(sizePolicy)
        self.SubPanel_sagittal.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_sagittal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_sagittal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_sagittal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_sagittal.setObjectName("SubPanel_sagittal")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SubPanel_sagittal)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Slider_sagittal = QtWidgets.QSlider(self.SubPanel_sagittal)
        self.Slider_sagittal.setAutoFillBackground(False)
        self.Slider_sagittal.setStyleSheet("")
        self.Slider_sagittal.setProperty("value", 50)
        self.Slider_sagittal.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_sagittal.setObjectName("Slider_sagittal")
        self.horizontalLayout_3.addWidget(self.Slider_sagittal)
        self.sliceNum_sagittal = QtWidgets.QLabel(self.SubPanel_sagittal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_sagittal.sizePolicy().hasHeightForWidth())
        self.sliceNum_sagittal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_sagittal.setFont(font)
        self.sliceNum_sagittal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_sagittal.setObjectName("sliceNum_sagittal")
        self.horizontalLayout_3.addWidget(self.sliceNum_sagittal)
        self.sliceNum_axial_3 = QtWidgets.QLabel(self.SubPanel_sagittal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_3.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_3.setFont(font)
        self.sliceNum_axial_3.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_3.setObjectName("sliceNum_axial_3")
        self.horizontalLayout_3.addWidget(self.sliceNum_axial_3)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_sagittal.addWidget(self.SubPanel_sagittal)
        self.verticalLayout_sagittal.setStretch(0, 20)
        self.verticalLayout_sagittal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_sagittal, 1, 1, 1, 1)
        self.verticalLayout_3D = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D.setSpacing(0)
        self.verticalLayout_3D.setObjectName("verticalLayout_3D")
        self.vtk_panel_3D = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D.setSizePolicy(sizePolicy)
        self.vtk_panel_3D.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_3D.setAutoFillBackground(False)
        self.vtk_panel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D.setLineWidth(0)
        self.vtk_panel_3D.setObjectName("vtk_panel_3D")
        self.verticalLayout_3D.addWidget(self.vtk_panel_3D)
        self.SubPanel_3D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D.setSizePolicy(sizePolicy)
        self.SubPanel_3D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D.setObjectName("SubPanel_3D")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SubPanel_3D)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sliceNum_axial_6 = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_6.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_6.setFont(font)
        self.sliceNum_axial_6.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_6.setObjectName("sliceNum_axial_6")
        self.horizontalLayout_5.addWidget(self.sliceNum_axial_6)
        self.sliceNum_axial_5 = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_5.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_5.setFont(font)
        self.sliceNum_axial_5.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_5.setObjectName("sliceNum_axial_5")
        self.horizontalLayout_5.addWidget(self.sliceNum_axial_5)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3D.addWidget(self.SubPanel_3D)
        self.verticalLayout_3D.setStretch(0, 20)
        self.verticalLayout_3D.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_3D, 0, 0, 1, 1)
        self.verticalLayout_coronal = QtWidgets.QVBoxLayout()
        self.verticalLayout_coronal.setSpacing(0)
        self.verticalLayout_coronal.setObjectName("verticalLayout_coronal")
        self.vtk_panel_coronal = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_coronal.sizePolicy().hasHeightForWidth())
        self.vtk_panel_coronal.setSizePolicy(sizePolicy)
        self.vtk_panel_coronal.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_coronal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_coronal.setLineWidth(0)
        self.vtk_panel_coronal.setObjectName("vtk_panel_coronal")
        self.verticalLayout_coronal.addWidget(self.vtk_panel_coronal)
        self.SubPanel_coronal = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_coronal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_coronal.sizePolicy().hasHeightForWidth())
        self.SubPanel_coronal.setSizePolicy(sizePolicy)
        self.SubPanel_coronal.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_coronal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_coronal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_coronal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_coronal.setObjectName("SubPanel_coronal")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.SubPanel_coronal)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Slider_coronal = QtWidgets.QSlider(self.SubPanel_coronal)
        self.Slider_coronal.setAutoFillBackground(False)
        self.Slider_coronal.setStyleSheet("")
        self.Slider_coronal.setProperty("value", 50)
        self.Slider_coronal.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_coronal.setObjectName("Slider_coronal")
        self.horizontalLayout_4.addWidget(self.Slider_coronal)
        self.sliceNum_coronal = QtWidgets.QLabel(self.SubPanel_coronal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_coronal.sizePolicy().hasHeightForWidth())
        self.sliceNum_coronal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_coronal.setFont(font)
        self.sliceNum_coronal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_coronal.setObjectName("sliceNum_coronal")
        self.horizontalLayout_4.addWidget(self.sliceNum_coronal)
        self.sliceNum_axial_4 = QtWidgets.QLabel(self.SubPanel_coronal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_axial_4.sizePolicy().hasHeightForWidth())
        self.sliceNum_axial_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_axial_4.setFont(font)
        self.sliceNum_axial_4.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_axial_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sliceNum_axial_4.setObjectName("sliceNum_axial_4")
        self.horizontalLayout_4.addWidget(self.sliceNum_axial_4)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_coronal.addWidget(self.SubPanel_coronal)
        self.verticalLayout_coronal.setStretch(0, 20)
        self.verticalLayout_coronal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_coronal, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("")
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionLoad_Image.setFont(font)
        self.actionLoad_Image.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionLoad_Image.setIconVisibleInMenu(True)
        self.actionLoad_Image.setProperty("shortcutVisibleInContextMenu", False)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_DICOM = QtWidgets.QAction(MainWindow)
        self.actionLoad_DICOM.setIcon(icon7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionLoad_DICOM.setFont(font)
        self.actionLoad_DICOM.setObjectName("actionLoad_DICOM")
        self.toolBar.addAction(self.actionLoad_DICOM)
        self.toolBar.addAction(self.actionLoad_Image)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.Slider_axial.valueChanged['int'].connect(self.sliceNum_axial.setNum)
        self.Slider_sagittal.valueChanged['int'].connect(self.sliceNum_sagittal.setNum)
        self.Slider_coronal.valueChanged['int'].connect(self.sliceNum_coronal.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BronchoVision"))
        self.groupBox_VB.setTitle(_translate("MainWindow", "Virtual Bronchoscopy"))
        self.btn_LoadPoints.setText(_translate("MainWindow", "    Load Tracker Points ..."))
        self.checkBox_showPoints.setText(_translate("MainWindow", "Show Tracker Points"))
        self.lbl_FrameNum.setText(_translate("MainWindow", "0 of 0"))
        self.btn_playCam.setText(_translate("MainWindow", "Start Virtual Camera"))
        self.btn_pauseCam.setText(_translate("MainWindow", "Start Virtual Camera"))
        self.btn_stopCam.setText(_translate("MainWindow", "Start Virtual Camera"))
        self.btn_ResetVB.setText(_translate("MainWindow", "   Reset"))
        self.groupBox_Tracker.setTitle(_translate("MainWindow", "Tracker"))
        self.btn_Connect.setText(_translate("MainWindow", "Connect Tracker"))
        self.btn_ToolsWindow.setText(_translate("MainWindow", "Tools Info"))
        self.groupBox_Viewports.setTitle(_translate("MainWindow", "Viewports"))
        self.btn_ResetViewports.setText(_translate("MainWindow", "   Reset Viewports"))
        self.sliceNum_axial.setText(_translate("MainWindow", "50"))
        self.sliceNum_axial_2.setText(_translate("MainWindow", "Axial"))
        self.sliceNum_sagittal.setText(_translate("MainWindow", "50"))
        self.sliceNum_axial_3.setText(_translate("MainWindow", "Sagittal"))
        self.sliceNum_axial_6.setText(_translate("MainWindow", "Virtual"))
        self.sliceNum_axial_5.setText(_translate("MainWindow", "3D"))
        self.sliceNum_coronal.setText(_translate("MainWindow", "50"))
        self.sliceNum_axial_4.setText(_translate("MainWindow", "Coronal"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image ..."))
        self.actionLoad_Image.setIconText(_translate("MainWindow", "Load Image ..."))
        self.actionLoad_Image.setToolTip(_translate("MainWindow", "Load Single Medical Images"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad_DICOM.setText(_translate("MainWindow", "Load DICOM ..."))
        self.actionLoad_DICOM.setIconText(_translate("MainWindow", "Load DICOM ..."))
        self.actionLoad_DICOM.setToolTip(_translate("MainWindow", "Load DICOM Series from Selected Directory"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
