# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.setWindowModality(QtCore.Qt.NonModal)
        MainWin.resize(1278, 884)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWin.sizePolicy().hasHeightForWidth())
        MainWin.setSizePolicy(sizePolicy)
        MainWin.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWin.setPalette(palette)
        MainWin.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWin.setAutoFillBackground(False)
        MainWin.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame_Left = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Left.sizePolicy().hasHeightForWidth())
        self.frame_Left.setSizePolicy(sizePolicy)
        self.frame_Left.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_Left.setAutoFillBackground(False)
        self.frame_Left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_Left.setLineWidth(1)
        self.frame_Left.setMidLineWidth(0)
        self.frame_Left.setObjectName("frame_Left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Left)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_VB = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_VB.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_VB.setFont(font)
        self.groupBox_VB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_VB.setAutoFillBackground(False)
        self.groupBox_VB.setStyleSheet("color: rgb(157, 205, 216);\n"
"border-color: rgb(114, 171, 171);")
        self.groupBox_VB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_VB.setFlat(True)
        self.groupBox_VB.setCheckable(False)
        self.groupBox_VB.setObjectName("groupBox_VB")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_VB)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_VB)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(50, 50,50);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_regMat = QtWidgets.QToolButton(self.frame_2)
        self.btn_regMat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_regMat.sizePolicy().hasHeightForWidth())
        self.btn_regMat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_regMat.setFont(font)
        self.btn_regMat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regMat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_regMat.setAutoFillBackground(False)
        self.btn_regMat.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/matrix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regMat.setIcon(icon)
        self.btn_regMat.setIconSize(QtCore.QSize(36, 28))
        self.btn_regMat.setCheckable(False)
        self.btn_regMat.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_regMat.setAutoRaise(True)
        self.btn_regMat.setObjectName("btn_regMat")
        self.verticalLayout_9.addWidget(self.btn_regMat)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(50, 50,50);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_LoadPoints = QtWidgets.QToolButton(self.frame)
        self.btn_LoadPoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_LoadPoints.sizePolicy().hasHeightForWidth())
        self.btn_LoadPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_LoadPoints.setFont(font)
        self.btn_LoadPoints.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_LoadPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_LoadPoints.setAutoFillBackground(False)
        self.btn_LoadPoints.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/trajectory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_LoadPoints.setIcon(icon1)
        self.btn_LoadPoints.setIconSize(QtCore.QSize(36, 28))
        self.btn_LoadPoints.setCheckable(False)
        self.btn_LoadPoints.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_LoadPoints.setAutoRaise(True)
        self.btn_LoadPoints.setObjectName("btn_LoadPoints")
        self.verticalLayout_3.addWidget(self.btn_LoadPoints)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.slider_Frames = QtWidgets.QSlider(self.frame)
        self.slider_Frames.setEnabled(False)
        self.slider_Frames.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Frames.setObjectName("slider_Frames")
        self.horizontalLayout_13.addWidget(self.slider_Frames)
        self.lbl_FrameNum = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FrameNum.sizePolicy().hasHeightForWidth())
        self.lbl_FrameNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_FrameNum.setFont(font)
        self.lbl_FrameNum.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_FrameNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FrameNum.setObjectName("lbl_FrameNum")
        self.horizontalLayout_13.addWidget(self.lbl_FrameNum)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_camButtons_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_camButtons_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_camButtons_3.setSpacing(0)
        self.horizontalLayout_camButtons_3.setObjectName("horizontalLayout_camButtons_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem1)
        self.btn_playCam = QtWidgets.QToolButton(self.frame)
        self.btn_playCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_playCam.sizePolicy().hasHeightForWidth())
        self.btn_playCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playCam.setFont(font)
        self.btn_playCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_playCam.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_playCam.setIcon(icon2)
        self.btn_playCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_playCam.setAutoRaise(True)
        self.btn_playCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_playCam.setObjectName("btn_playCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_playCam)
        self.btn_pauseCam = QtWidgets.QToolButton(self.frame)
        self.btn_pauseCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pauseCam.sizePolicy().hasHeightForWidth())
        self.btn_pauseCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pauseCam.setFont(font)
        self.btn_pauseCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pauseCam.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pauseCam.setIcon(icon3)
        self.btn_pauseCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_pauseCam.setAutoRaise(True)
        self.btn_pauseCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_pauseCam.setObjectName("btn_pauseCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_pauseCam)
        self.btn_stopCam = QtWidgets.QToolButton(self.frame)
        self.btn_stopCam.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stopCam.sizePolicy().hasHeightForWidth())
        self.btn_stopCam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stopCam.setFont(font)
        self.btn_stopCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stopCam.setAutoFillBackground(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stopCam.setIcon(icon4)
        self.btn_stopCam.setIconSize(QtCore.QSize(34, 34))
        self.btn_stopCam.setAutoRaise(True)
        self.btn_stopCam.setArrowType(QtCore.Qt.NoArrow)
        self.btn_stopCam.setObjectName("btn_stopCam")
        self.horizontalLayout_camButtons_3.addWidget(self.btn_stopCam)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_camButtons_3.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_camButtons_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.checkBox_showPoints = QtWidgets.QCheckBox(self.frame)
        self.checkBox_showPoints.setEnabled(False)
        self.checkBox_showPoints.setChecked(True)
        self.checkBox_showPoints.setObjectName("checkBox_showPoints")
        self.verticalLayout_3.addWidget(self.checkBox_showPoints)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_7.addWidget(self.frame)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.btn_ResetVB = QtWidgets.QToolButton(self.groupBox_VB)
        self.btn_ResetVB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetVB.sizePolicy().hasHeightForWidth())
        self.btn_ResetVB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetVB.setFont(font)
        self.btn_ResetVB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetVB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetVB.setAutoFillBackground(False)
        self.btn_ResetVB.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetVB.setIcon(icon5)
        self.btn_ResetVB.setIconSize(QtCore.QSize(36, 28))
        self.btn_ResetVB.setCheckable(False)
        self.btn_ResetVB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetVB.setAutoRaise(True)
        self.btn_ResetVB.setObjectName("btn_ResetVB")
        self.verticalLayout_2.addWidget(self.btn_ResetVB)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_VB)
        self.groupBox_Tracker = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_Tracker.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Tracker.setFont(font)
        self.groupBox_Tracker.setAutoFillBackground(False)
        self.groupBox_Tracker.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Tracker.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Tracker.setFlat(True)
        self.groupBox_Tracker.setCheckable(False)
        self.groupBox_Tracker.setObjectName("groupBox_Tracker")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Tracker)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_Connect = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_Connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Connect.sizePolicy().hasHeightForWidth())
        self.btn_Connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_Connect.setFont(font)
        self.btn_Connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Connect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Connect.setAutoFillBackground(False)
        self.btn_Connect.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/tracker_disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Connect.setIcon(icon6)
        self.btn_Connect.setIconSize(QtCore.QSize(36, 28))
        self.btn_Connect.setCheckable(False)
        self.btn_Connect.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_Connect.setAutoRaise(True)
        self.btn_Connect.setObjectName("btn_Connect")
        self.verticalLayout_4.addWidget(self.btn_Connect)
        self.btn_ToolsWindow = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_ToolsWindow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ToolsWindow.sizePolicy().hasHeightForWidth())
        self.btn_ToolsWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ToolsWindow.setFont(font)
        self.btn_ToolsWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ToolsWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ToolsWindow.setAutoFillBackground(False)
        self.btn_ToolsWindow.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/Tools_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ToolsWindow.setIcon(icon7)
        self.btn_ToolsWindow.setIconSize(QtCore.QSize(36, 28))
        self.btn_ToolsWindow.setCheckable(False)
        self.btn_ToolsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ToolsWindow.setAutoRaise(True)
        self.btn_ToolsWindow.setObjectName("btn_ToolsWindow")
        self.verticalLayout_4.addWidget(self.btn_ToolsWindow)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_recordToolRef = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_recordToolRef.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_recordToolRef.sizePolicy().hasHeightForWidth())
        self.btn_recordToolRef.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_recordToolRef.setFont(font)
        self.btn_recordToolRef.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_recordToolRef.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_recordToolRef.setAutoFillBackground(False)
        self.btn_recordToolRef.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/rec_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_recordToolRef.setIcon(icon8)
        self.btn_recordToolRef.setIconSize(QtCore.QSize(36, 28))
        self.btn_recordToolRef.setCheckable(False)
        self.btn_recordToolRef.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_recordToolRef.setAutoRaise(True)
        self.btn_recordToolRef.setObjectName("btn_recordToolRef")
        self.horizontalLayout_10.addWidget(self.btn_recordToolRef)
        self.btn_saveToolRefCoords = QtWidgets.QToolButton(self.groupBox_Tracker)
        self.btn_saveToolRefCoords.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_saveToolRefCoords.sizePolicy().hasHeightForWidth())
        self.btn_saveToolRefCoords.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_saveToolRefCoords.setFont(font)
        self.btn_saveToolRefCoords.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_saveToolRefCoords.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_saveToolRefCoords.setAutoFillBackground(False)
        self.btn_saveToolRefCoords.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.btn_saveToolRefCoords.setIconSize(QtCore.QSize(36, 28))
        self.btn_saveToolRefCoords.setCheckable(False)
        self.btn_saveToolRefCoords.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_saveToolRefCoords.setAutoRaise(True)
        self.btn_saveToolRefCoords.setObjectName("btn_saveToolRefCoords")
        self.horizontalLayout_10.addWidget(self.btn_saveToolRefCoords)
        self.horizontalLayout_10.setStretch(0, 4)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.groupBox_Tracker)
        self.groupBox_Viewports = QtWidgets.QGroupBox(self.frame_Left)
        self.groupBox_Viewports.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_Viewports.setFont(font)
        self.groupBox_Viewports.setAutoFillBackground(False)
        self.groupBox_Viewports.setStyleSheet("color: rgb(157, 205, 216);")
        self.groupBox_Viewports.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_Viewports.setFlat(True)
        self.groupBox_Viewports.setCheckable(False)
        self.groupBox_Viewports.setObjectName("groupBox_Viewports")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Viewports)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.comboBox_2DView = QtWidgets.QComboBox(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2DView.sizePolicy().hasHeightForWidth())
        self.comboBox_2DView.setSizePolicy(sizePolicy)
        self.comboBox_2DView.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.comboBox_2DView.setFont(font)
        self.comboBox_2DView.setAutoFillBackground(True)
        self.comboBox_2DView.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.comboBox_2DView.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_2DView.setFrame(False)
        self.comboBox_2DView.setObjectName("comboBox_2DView")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.comboBox_2DView.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_2DView)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Viewports)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Viewports)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.slider_threshold3D = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D.setEnabled(True)
        self.slider_threshold3D.setMinimum(-2000)
        self.slider_threshold3D.setMaximum(1000)
        self.slider_threshold3D.setSingleStep(10)
        self.slider_threshold3D.setPageStep(100)
        self.slider_threshold3D.setProperty("value", -600)
        self.slider_threshold3D.setTracking(False)
        self.slider_threshold3D.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D.setObjectName("slider_threshold3D")
        self.horizontalLayout_12.addWidget(self.slider_threshold3D)
        self.lbl_threshold3D = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D.setSizePolicy(sizePolicy)
        self.lbl_threshold3D.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_threshold3D.setFont(font)
        self.lbl_threshold3D.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D.setObjectName("lbl_threshold3D")
        self.horizontalLayout_12.addWidget(self.lbl_threshold3D)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Viewports)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.slider_threshold3D_2 = QtWidgets.QSlider(self.groupBox_Viewports)
        self.slider_threshold3D_2.setEnabled(True)
        self.slider_threshold3D_2.setMinimum(-2000)
        self.slider_threshold3D_2.setMaximum(1000)
        self.slider_threshold3D_2.setSingleStep(10)
        self.slider_threshold3D_2.setPageStep(100)
        self.slider_threshold3D_2.setProperty("value", 250)
        self.slider_threshold3D_2.setTracking(False)
        self.slider_threshold3D_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold3D_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_threshold3D_2.setObjectName("slider_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.slider_threshold3D_2)
        self.lbl_threshold3D_2 = QtWidgets.QLabel(self.groupBox_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_threshold3D_2.sizePolicy().hasHeightForWidth())
        self.lbl_threshold3D_2.setSizePolicy(sizePolicy)
        self.lbl_threshold3D_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_threshold3D_2.setFont(font)
        self.lbl_threshold3D_2.setStyleSheet("color: rgb(157, 205, 216);")
        self.lbl_threshold3D_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_threshold3D_2.setObjectName("lbl_threshold3D_2")
        self.horizontalLayout_14.addWidget(self.lbl_threshold3D_2)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 2)
        self.horizontalLayout_14.setStretch(2, 10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.btn_ResetViewports = QtWidgets.QToolButton(self.groupBox_Viewports)
        self.btn_ResetViewports.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ResetViewports.sizePolicy().hasHeightForWidth())
        self.btn_ResetViewports.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ResetViewports.setFont(font)
        self.btn_ResetViewports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ResetViewports.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ResetViewports.setAutoFillBackground(False)
        self.btn_ResetViewports.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/resetViews.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ResetViewports.setIcon(icon9)
        self.btn_ResetViewports.setIconSize(QtCore.QSize(36, 28))
        self.btn_ResetViewports.setCheckable(False)
        self.btn_ResetViewports.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btn_ResetViewports.setAutoRaise(True)
        self.btn_ResetViewports.setObjectName("btn_ResetViewports")
        self.verticalLayout_5.addWidget(self.btn_ResetViewports)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.groupBox_Viewports)
        self.label = QtWidgets.QLabel(self.frame_Left)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(250, 30))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo/logo_transparent.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.frame_Viewports = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Viewports.sizePolicy().hasHeightForWidth())
        self.frame_Viewports.setSizePolicy(sizePolicy)
        self.frame_Viewports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Viewports.setObjectName("frame_Viewports")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Viewports)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3D = QtWidgets.QVBoxLayout()
        self.verticalLayout_3D.setSpacing(0)
        self.verticalLayout_3D.setObjectName("verticalLayout_3D")
        self.vtk_panel_3D_1 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_1.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_1.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_1.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_3D_1.setAutoFillBackground(False)
        self.vtk_panel_3D_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_1.setLineWidth(0)
        self.vtk_panel_3D_1.setObjectName("vtk_panel_3D_1")
        self.verticalLayout_3D.addWidget(self.vtk_panel_3D_1)
        self.SubPanel_3D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D.setSizePolicy(sizePolicy)
        self.SubPanel_3D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D.setObjectName("SubPanel_3D")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.SubPanel_3D)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.view1_desc = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view1_desc.sizePolicy().hasHeightForWidth())
        self.view1_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view1_desc.setFont(font)
        self.view1_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view1_desc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.view1_desc.setObjectName("view1_desc")
        self.horizontalLayout_5.addWidget(self.view1_desc)
        self.view1_title = QtWidgets.QLabel(self.SubPanel_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view1_title.sizePolicy().hasHeightForWidth())
        self.view1_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view1_title.setFont(font)
        self.view1_title.setStyleSheet("color: rgb(157, 205, 216);")
        self.view1_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.view1_title.setObjectName("view1_title")
        self.horizontalLayout_5.addWidget(self.view1_title)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3D.addWidget(self.SubPanel_3D)
        self.verticalLayout_3D.setStretch(0, 20)
        self.verticalLayout_3D.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_3D, 0, 0, 1, 1)
        self.verticalLayout_coronal = QtWidgets.QVBoxLayout()
        self.verticalLayout_coronal.setSpacing(0)
        self.verticalLayout_coronal.setObjectName("verticalLayout_coronal")
        self.vtk_panel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_endoscope.sizePolicy().hasHeightForWidth())
        self.vtk_panel_endoscope.setSizePolicy(sizePolicy)
        self.vtk_panel_endoscope.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_endoscope.setLineWidth(0)
        self.vtk_panel_endoscope.setObjectName("vtk_panel_endoscope")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.vtk_panel_endoscope)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_coronal.addWidget(self.vtk_panel_endoscope)
        self.SubPanel_endoscope = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_endoscope.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_endoscope.sizePolicy().hasHeightForWidth())
        self.SubPanel_endoscope.setSizePolicy(sizePolicy)
        self.SubPanel_endoscope.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_endoscope.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_endoscope.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_endoscope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_endoscope.setObjectName("SubPanel_endoscope")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.SubPanel_endoscope)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.view3_desc = QtWidgets.QLabel(self.SubPanel_endoscope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3_desc.sizePolicy().hasHeightForWidth())
        self.view3_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view3_desc.setFont(font)
        self.view3_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view3_desc.setObjectName("view3_desc")
        self.horizontalLayout_4.addWidget(self.view3_desc)
        self.view3_title = QtWidgets.QLabel(self.SubPanel_endoscope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3_title.sizePolicy().hasHeightForWidth())
        self.view3_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view3_title.setFont(font)
        self.view3_title.setStyleSheet("color: rgb(157, 205, 216);")
        self.view3_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.view3_title.setObjectName("view3_title")
        self.horizontalLayout_4.addWidget(self.view3_title)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_coronal.addWidget(self.SubPanel_endoscope)
        self.verticalLayout_coronal.setStretch(0, 20)
        self.verticalLayout_coronal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_coronal, 1, 0, 1, 1)
        self.verticalLayout_sagittal = QtWidgets.QVBoxLayout()
        self.verticalLayout_sagittal.setSpacing(0)
        self.verticalLayout_sagittal.setObjectName("verticalLayout_sagittal")
        self.vtk_panel_2D = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_2D.sizePolicy().hasHeightForWidth())
        self.vtk_panel_2D.setSizePolicy(sizePolicy)
        self.vtk_panel_2D.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_2D.setLineWidth(0)
        self.vtk_panel_2D.setObjectName("vtk_panel_2D")
        self.verticalLayout_sagittal.addWidget(self.vtk_panel_2D)
        self.SubPanel_2D = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_2D.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_2D.sizePolicy().hasHeightForWidth())
        self.SubPanel_2D.setSizePolicy(sizePolicy)
        self.SubPanel_2D.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_2D.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_2D.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_2D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_2D.setObjectName("SubPanel_2D")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.SubPanel_2D)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Slider_2D = QtWidgets.QSlider(self.SubPanel_2D)
        self.Slider_2D.setAutoFillBackground(False)
        self.Slider_2D.setStyleSheet("")
        self.Slider_2D.setProperty("value", 50)
        self.Slider_2D.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2D.setObjectName("Slider_2D")
        self.horizontalLayout_3.addWidget(self.Slider_2D)
        self.sliceNum_sagittal = QtWidgets.QLabel(self.SubPanel_2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceNum_sagittal.sizePolicy().hasHeightForWidth())
        self.sliceNum_sagittal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sliceNum_sagittal.setFont(font)
        self.sliceNum_sagittal.setStyleSheet("color: rgb(157, 205, 216);")
        self.sliceNum_sagittal.setObjectName("sliceNum_sagittal")
        self.horizontalLayout_3.addWidget(self.sliceNum_sagittal)
        self.view4_title = QtWidgets.QLabel(self.SubPanel_2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view4_title.sizePolicy().hasHeightForWidth())
        self.view4_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view4_title.setFont(font)
        self.view4_title.setStyleSheet("color: rgb(157, 205, 216);")
        self.view4_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.view4_title.setObjectName("view4_title")
        self.horizontalLayout_3.addWidget(self.view4_title)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_sagittal.addWidget(self.SubPanel_2D)
        self.verticalLayout_sagittal.setStretch(0, 20)
        self.verticalLayout_sagittal.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_sagittal, 1, 1, 1, 1)
        self.verticalLayout_axial = QtWidgets.QVBoxLayout()
        self.verticalLayout_axial.setSpacing(0)
        self.verticalLayout_axial.setObjectName("verticalLayout_axial")
        self.vtk_panel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel_3D_2.sizePolicy().hasHeightForWidth())
        self.vtk_panel_3D_2.setSizePolicy(sizePolicy)
        self.vtk_panel_3D_2.setMinimumSize(QtCore.QSize(0, 0))
        self.vtk_panel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vtk_panel_3D_2.setLineWidth(0)
        self.vtk_panel_3D_2.setObjectName("vtk_panel_3D_2")
        self.verticalLayout_axial.addWidget(self.vtk_panel_3D_2)
        self.SubPanel_3D_2 = QtWidgets.QFrame(self.frame_Viewports)
        self.SubPanel_3D_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubPanel_3D_2.sizePolicy().hasHeightForWidth())
        self.SubPanel_3D_2.setSizePolicy(sizePolicy)
        self.SubPanel_3D_2.setBaseSize(QtCore.QSize(0, 0))
        self.SubPanel_3D_2.setAutoFillBackground(False)
        self.SubPanel_3D_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SubPanel_3D_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SubPanel_3D_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubPanel_3D_2.setObjectName("SubPanel_3D_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.SubPanel_3D_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view2_desc = QtWidgets.QLabel(self.SubPanel_3D_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2_desc.sizePolicy().hasHeightForWidth())
        self.view2_desc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view2_desc.setFont(font)
        self.view2_desc.setStyleSheet("color: rgb(157, 205, 216);")
        self.view2_desc.setObjectName("view2_desc")
        self.horizontalLayout_2.addWidget(self.view2_desc)
        self.view2_title = QtWidgets.QLabel(self.SubPanel_3D_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2_title.sizePolicy().hasHeightForWidth())
        self.view2_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.view2_title.setFont(font)
        self.view2_title.setStyleSheet("color: rgb(157, 205, 216);")
        self.view2_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.view2_title.setObjectName("view2_title")
        self.horizontalLayout_2.addWidget(self.view2_title)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_axial.addWidget(self.SubPanel_3D_2)
        self.verticalLayout_axial.setStretch(0, 20)
        self.verticalLayout_axial.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout_axial, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.splitter)
        MainWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWin)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("")
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWin.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Image = QtWidgets.QAction(MainWin)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionLoad_Image.setFont(font)
        self.actionLoad_Image.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionLoad_Image.setIconVisibleInMenu(True)
        self.actionLoad_Image.setProperty("shortcutVisibleInContextMenu", False)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionExit = QtWidgets.QAction(MainWin)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_DICOM = QtWidgets.QAction(MainWin)
        self.actionLoad_DICOM.setIcon(icon10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionLoad_DICOM.setFont(font)
        self.actionLoad_DICOM.setObjectName("actionLoad_DICOM")
        self.toolBar.addAction(self.actionLoad_DICOM)
        self.toolBar.addAction(self.actionLoad_Image)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox_2DView.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWin.close)
        self.Slider_2D.valueChanged['int'].connect(self.sliceNum_sagittal.setNum)
        self.slider_threshold3D.valueChanged['int'].connect(self.lbl_threshold3D.setNum)
        self.slider_threshold3D_2.valueChanged['int'].connect(self.lbl_threshold3D_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "BronchoVision"))
        self.groupBox_VB.setTitle(_translate("MainWin", "Virtual Bronchoscopy"))
        self.btn_regMat.setText(_translate("MainWin", "Registration Matrix ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWin", "Online"))
        self.btn_LoadPoints.setText(_translate("MainWin", "    Load Tracker Points ..."))
        self.lbl_FrameNum.setText(_translate("MainWin", "0 of 0"))
        self.btn_playCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_pauseCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.btn_stopCam.setText(_translate("MainWin", "Start Virtual Camera"))
        self.checkBox_showPoints.setText(_translate("MainWin", "Show Tracker Points"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWin", "Offline"))
        self.btn_ResetVB.setText(_translate("MainWin", "   Reset VB"))
        self.groupBox_Tracker.setTitle(_translate("MainWin", "Tracker"))
        self.btn_Connect.setText(_translate("MainWin", "Connect Tracker"))
        self.btn_ToolsWindow.setText(_translate("MainWin", "Tools Info ..."))
        self.btn_recordToolRef.setText(_translate("MainWin", "Start Record"))
        self.btn_saveToolRefCoords.setText(_translate("MainWin", "Save ..."))
        self.groupBox_Viewports.setTitle(_translate("MainWin", "Viewports"))
        self.label_2.setText(_translate("MainWin", "2D View"))
        self.comboBox_2DView.setCurrentText(_translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(0, _translate("MainWin", "Axial"))
        self.comboBox_2DView.setItemText(1, _translate("MainWin", "Coronal"))
        self.comboBox_2DView.setItemText(2, _translate("MainWin", "Sagittal"))
        self.label_3.setText(_translate("MainWin", "3D Views Threshold"))
        self.label_4.setText(_translate("MainWin", "Virtual"))
        self.lbl_threshold3D.setText(_translate("MainWin", "-600"))
        self.label_5.setText(_translate("MainWin", "Normal"))
        self.lbl_threshold3D_2.setText(_translate("MainWin", "250"))
        self.btn_ResetViewports.setText(_translate("MainWin", "   Reset Viewports"))
        self.view1_desc.setText(_translate("MainWin", "Virtual"))
        self.view1_title.setText(_translate("MainWin", "3D"))
        self.view3_desc.setText(_translate("MainWin", "Endoscope"))
        self.view3_title.setText(_translate("MainWin", "Video"))
        self.sliceNum_sagittal.setText(_translate("MainWin", "50"))
        self.view4_title.setText(_translate("MainWin", "2D"))
        self.view2_desc.setText(_translate("MainWin", "Normal"))
        self.view2_title.setText(_translate("MainWin", "3D"))
        self.toolBar.setWindowTitle(_translate("MainWin", "toolBar"))
        self.actionLoad_Image.setText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setIconText(_translate("MainWin", "Load Image ..."))
        self.actionLoad_Image.setToolTip(_translate("MainWin", "Load Single Medical Images"))
        self.actionExit.setText(_translate("MainWin", "Exit"))
        self.actionLoad_DICOM.setText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setIconText(_translate("MainWin", "Load DICOM ..."))
        self.actionLoad_DICOM.setToolTip(_translate("MainWin", "Load DICOM Series from Selected Directory"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec_())

